# Part-of-Speech Tagging for Danish

:::{note}
This section, "Working in Languages Beyond English," is co-authored with <a href="http://www.quinndombrowski.com/">Quinn Dombrowski</a>, the Academic Technology Specialist at Stanford University and a leading voice in multilingual digital humanities. I'm grateful to Quinn for helping expand this textbook to serve languages beyond English. 
:::

In this lesson, we're going to learn about the textual analysis methods *part-of-speech tagging* and *keyword extraction* for Danish texts. These methods will help us computationally parse sentences and better understand words in context.

---

## spaCy and Natural Language Processing (NLP)

To computationally identify parts of speech, we're going to use the natural language processing library spaCy. For a more extensive introduction to NLP and spaCy, see the previous lesson.

To parse sentences, spaCy relies on machine learning models that were trained on large amounts of labeled text data. If you've used the preprocessing or named entity recognition notebooks for this language, you can skip the steps for installing spaCy and downloading the language model.

## Install spaCy

To use spaCy, we first need to install the library.

In [ ]:
%pip install -U spacy

## Import Libraries

Then we're going to import `spacy` and `displacy`, a special spaCy module for visualization.

In [1]:
import spacy
from spacy import displacy
from collections import Counter
import pandas as pd
pd.set_option("display.max_rows", 400)
pd.set_option("display.max_colwidth", 400)

We're also going to import the `Counter` module for counting nouns, verbs, adjectives, etc., and the `pandas` library for organizing and displaying data (we're also changing the pandas default max row and column width display setting).

## Download Language Model

Next we need to download the Danish-language model (`da_core_news_md`), which will be processing and making predictions about our texts. This is the model that was trained on a corpus of news and nonfiction. You can download the `da_core_news_md` model by running the cell below:

In [ ]:
# ALPS unsupported shell command: !python -m spacy download da_core_news_md

*Note: spaCy offers [models for other languages](https://spacy.io/usage/models#languages) including Chinese, German, French, Spanish, Portuguese, Russian, Italian, Dutch, Danish, Greek, Norwegian, and Lithuanian*.  

*spaCy offers language and tokenization support for other language via external dependencies — such as [PyviKonlpy](https://github.com/konlpy/konlpy) for Korean.*

## Load Language Model

Once the model is downloaded, we need to load it with `spacy.load()` and assign it to the variable `nlp`.

In [2]:
nlp = spacy.load('da_core_news_md')

## Create a Processed spaCy Document

Whenever we use spaCy, our first step will be to create a processed spaCy `document` with the loaded NLP model `nlp()`. Most of the heavy NLP lifting is done in this line of code. After processing, the `document` object will contain tons of juicy language data — named entities, sentence boundaries, parts of speech — and the rest of our work will be devoted to accessing this information.

In [3]:
filepath = '../texts/da.txt'
text = open(filepath, encoding='utf-8').read()
document = nlp(text)

## spaCy Part-of-Speech Tagging
The tags that spaCy uses for part-of-speech are based on work done by [Universal Dependencies](https://universaldependencies.org/), an effort to create a set of part-of-speech tags that work across many different languages. Texts from various languages are annotated using this common set of tags, and contributed to a common repository that can be used to train models like spaCy.

The Universal Dependencies page has information about the annotated corpora available for each language; it's worth looking into the corpora that were annotated for your language.

| POS   | Description               | Examples                                      |
|:-----:|:-------------------------:|:---------------------------------------------:|
| ADJ   | adjective                 | big, old, green, incomprehensible, first      |
| ADP   | adposition                | in, to, during                                |
| ADV   | adverb                    | very, tomorrow, down, where, there            |
| AUX   | auxiliary                 | is, has (done), will (do), should (do)        |
| CONJ  | conjunction               | and, or, but                                  |
| CCONJ | coordinating conjunction  | and, or, but                                  |
| DET   | determiner                | a, an, the                                    |
| INTJ  | interjection              | psst, ouch, bravo, hello                      |
| NOUN  | noun                      | girl, cat, tree, air, beauty                  |
| NUM   | numeral                   | 1, 2017, one, seventy-seven, IV, MMXIV        |
| PART  | particle                  | ’s, not,                                      |
| PRON  | pronoun                   | I, you, he, she, myself, themselves, somebody |
| PROPN | proper noun               | Mary, John, London, NATO, HBO                 |
| PUNCT | punctuation               | ., (, ), ?                                    |
| SCONJ | subordinating conjunction | if, while, that                               |
| SYM   | symbol                    | $, %, §, ©, +, −, ×, ÷, =, :), 😝             |
| VERB  | verb                      | run, runs, running, eat, ate, eating          |
| X     | other                     | sfpksdpsxmsa                                  |
| SPACE | space                     |                                               |

Above is a POS chart taken from [spaCy's website](https://spacy.io/api/annotation#named-entities), which shows the different parts of speech that spaCy can identify as well as their corresponding labels. To quickly see spaCy's POS tagging in action, we can use the [spaCy module `displacy`](https://spacy.io/usage/visualizers#ent) on our sample `document` with the `style=` parameter set to "dep" (short for dependency parsing):

## Get Part-Of-Speech Tags

To get part of speech tags for every word in a document, we have to iterate through all the tokens in the document and pull out the `.lemma_` attribute for each token, which gives us the un-inflected version of the word. We'll also pull out the  `.pos_` attribute for each token. We can get even finer-grained dependency information with the attribute `.dep_`.

In [17]:
for token in document:
    print(token.lemma_, token.pos_, token.dep_)

EVANGELINES PROPN ROOT

  SPACE
GENVORDIGHEDER NOUN flat


  SPACE
TIL ADP case

  SPACE
KVINDER NOUN ROOT
MED ADP case
RØDT NOUN amod
HAAR NOUN nmod





  SPACE
ELINOR PROPN ROOT
GLYN PROPN flat


  SPACE
EVANGELINES PROPN flat

  SPACE
GENVORDIGHEDER NOUN conj


  SPACE
AUTORISERET NOUN flat
OVERSÆTTELSE NOUN ROOT

  SPACE
FOR ADP case
NORGE PROPN ROOT
OG CCONJ cc
DANMARK PROPN conj
AF ADP case

  SPACE
HEDVIG PROPN obl
MAGNUSSEN PROPN flat


  SPACE
NY ADJ amod
UDGAVE NOUN flat


  SPACE
MARTINS PROPN flat
FORLAG PROPN conj

  SPACE
KØBENHAVN PROPN conj
& CCONJ cc
KRISTIANIA PROPN conj

  SPACE
MCMXXI NOUN conj





  SPACE
MARTIN'S X ROOT
FORLAGSTRYKKERI NOUN conj
, PUNCT punct
KØBENHAVN PROPN amod





 SPACE
BEGYNDELSEN PROPN nmod
PAA PROPN appos
EVANGELINES PROPN flat
DAGBOG NOUN conj



                                                SPACE
_ PUNCT punct
Branches PROPN list
Park PROPN flat
_ PUNCT punct
. PUNCT punct

                                               SPACE
Den DET det
3. ADJ amod
November NOUN ROOT
1904 NUM nmod
. PUNCT punct


 SPACE
Jeg PRON nsubj
vild ADJ nsubj
saa ADV advmod
gerne ADV advmod
vide VERB ROOT
, PUNCT punct
om SCONJ mark
det PRON nsubj
være AUX cop
morsom ADJ amod
at PART mark
være AUX cop
en DET det
Eventyrerske NOUN amod
, PUNCT punct

 SPACE
for CCONJ mark
det PRON nsubj
være AUX cop
øjensynlig ADV advmod
det PRON obl
, PUNCT punct
jeg PRON nsubj
nu ADV advmod
maa AUX aux
blive VERB acl:relcl
. PUNCT punct
Jeg PRON nsubj
have AUX aux
læst VERB ROOT
alt ADJ amod
mulig ADJ advmod

 SPACE
om ADP case
det PRON obl
i ADP case
en DET det
Bog NOUN obl
; PUNCT punct
det PRON nsubj
være AUX conj
at PART mark
se VERB obj
godte ADV amod
ud ADV advmod
, PUNCT punct
og CCONJ cc
ikke ADV advmod
at PART mark
hav VERB acl:relcl
nogen PRON obj
at PART mark
leve VERB acl:relcl

 SPACE
af ADP mark
, PUNCT punct
og CCONJ cc
dog ADV advmod
hav VERB conj
Fornøjelse NOUN obj
af ADP case
Livet NOUN nmod
-- PUNCT punct
og CCONJ cc
det PRON obj
have VERB conj
jeg PRON nsubj
i ADP case
Sinde NOUN obl
! PUNCT punct
Jeg PRON nsubj

 SPACE
have AUX aux
ganske ADV advmod
vist VERB ROOT
ingenting PRON obl
at PART mark
leve VERB acl:relcl
af ADP mark
, PUNCT punct
for CCONJ dep
man PRON nsubj
kunne AUX aux
ikke ADV advmod
regne VERB dep
300 NUM nummod
Pund NOUN obj

 SPACE
om ADP case
Aaret NOUN nmod
for ADP case
nogen PRON det
videre ADV nmod
-- PUNCT punct
jeg PRON nsubj
være AUX cop
overordentlig ADV advmod
køn NOUN conj
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
véd VERB conj
det PRON obj

 SPACE
godte ADJ amod
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
forstaar VERB conj
at PART mark
sætte VERB obj
min DET det
Haar NOUN obj
og CCONJ cc
tag VERB conj
min DET det
Hatte NOUN obj
paa ADV obl:loc
og CCONJ cc
den PRON det

 SPACE
Slags NOUN obj
Ting NOUN nmod
, PUNCT punct
saa SCONJ mark
jeg PRON nsubj
være AUX cop
naturligvis ADV advmod
Eventyrerske PROPN conj
! PUNCT punct
Jeg PRON nsubj
være AUX cop
ikke ADV advmod
bestemt ADV ROOT

 SPACE
til ADP mark
at PART mark
spille VERB advcl
den DET det
Rolle NOUN obj
. PUNCT punct
-- PUNCT punct
Fru PROPN nsubj
Carruthers PROPN flat
adoptere VERB ccomp
jeg PRON obj
for ADP mark
at PART mark

 SPACE
efterlade VERB advcl
jeg PRON iobj
sin DET det
Formue NOUN obj
, PUNCT punct
da SCONJ mark
hun PRON nsubj
den DET det
Gang NOUN nmod
være AUX cop
Uvenner NOUN nsubj
mede ADP case
sin DET det
Arving NOUN nmod
, PUNCT punct

 SPACE
som ADP case
_ PUNCT punct
skulde NOUN amod
_ AUX punct
arve VERB ROOT
Godset NOUN obj
. PUNCT punct
Saa ADV nsubj
være AUX cop
hun PRON nsubj
saa ADV advmod
inkonsekvent ADJ ROOT
, PUNCT punct
at SCONJ mark
hun PRON nsubj
ikke ADV advmod

 SPACE
skrive VERB acl:relcl
en DET det
ordentlig ADJ amod
Testamente NOUN obj
-- PUNCT punct
derfor ADV advmod
være AUX cop
det PRON dep
, PUNCT punct
at SCONJ mark
det DET det
Menneske NOUN nsubj
skulle AUX aux

 SPACE
hav VERB acl:relcl
alt ADJ obj
, PUNCT punct
og CCONJ dep
jeg PRON nsubj
ingenting PRON conj
. PUNCT punct


 SPACE
Jeg PRON nsubj
være AUX cop
tyv NUM nummod
Aar NOUN ROOT
, PUNCT punct
og CCONJ cc
lige ADV advmod
indtil ADP case
forrige ADJ amod
Uge NOUN nsubj
, PUNCT punct
da SCONJ mark
Fru PROPN nsubj
Carruthers PROPN flat
blive AUX cop

 SPACE
syg ADJ advmod
og CCONJ cc
dø VERB conj
paa ADP advmod
én DET det
og CCONJ dep
samme ADJ amod
Dag NOUN conj
, PUNCT punct
have VERB conj
jeg PRON nsubj
det PRON det
sommetider NOUN obj
megen ADV advmod

 SPACE
behagelig ADJ amod
, PUNCT punct
naar SCONJ mark
hun PRON nsubj
være VERB advmod
i ADP case
godte ADJ amod
Humør NOUN obl
. PUNCT punct


 SPACE
Det PRON nsubj
kunne AUX aux
ikke ADV advmod
nytte VERB ROOT
at PART mark
lade VERB obj
, PUNCT punct
som ADV mark
om ADP fixed
man PRON nsubj
kunne AUX aux
lide VERB ccomp
Folk NOUN obj
, PUNCT punct
fordi SCONJ mark
de PRON nsubj
være AUX cop

 SPACE
dø ADJ advmod
, PUNCT punct
naar SCONJ mark
man PRON nsubj
ville AUX aux
skrive VERB advmod
sin DET det
virkelig ADJ amod
Tanker NOUN obj
. PUNCT punct
For ADP case
det DET det
meste ADJ obl
hade VERB ROOT

 SPACE
jeg PRON nsubj
Fru PROPN obj
Carruthers PROPN flat
. PUNCT punct
Det PRON nsubj
være AUX cop
ganske ADV advmod
umulig ADJ ROOT
at PART mark
gøre VERB acl:relcl
hun PRON obj
tilpasse ADV amod
. PUNCT punct
Hun PRON nsubj

 SPACE
have VERB ROOT
ikke ADV advmod
Begreb NOUN obj
om ADP case
Retfærdighed NOUN nmod
, PUNCT punct
eller CCONJ cc
om ADP case
nogen DET det
anden PRON det
ende ADP case
sin DET det
eg ADJ amod

 SPACE
Bekvemmelighed NOUN dep
, PUNCT punct
og CCONJ cc
om ADP case
hvor ADV advmod
megen ADV advmod
anden DET det
Mennesker NOUN nsubj
kunde NOUN nmod
bidrage VERB conj
til ADP case

 SPACE
hendes DET det
Fornøjelse NOUN obl
. PUNCT punct


 SPACE
Grunden NOUN nsubj
til ADP mark
, PUNCT punct
at SCONJ mark
hun PRON nsubj
i ADP case
det DET det
hele NOUN obl
tag VERB fixed
komme NOUN advcl
til ADP mark
at PART mark
gøre VERB advcl
nogen PRON obj
for ADP case
jeg PRON obl
, PUNCT punct

 SPACE
være AUX cop
den PRON obl
, PUNCT punct
at SCONJ mark
hun PRON nsubj
have AUX aux
være AUX aux
forelske VERB acl:relcl
i ADP case
Papa PROPN obl
, PUNCT punct
og CCONJ cc
da SCONJ mark
han PRON nsubj
gifte VERB conj
sig PRON obj

 SPACE
mede ADP case
stakkels ADJ amod
Mama PROPN obl
-- PUNCT punct
som ADP obj
slette ADV advmod
ingen DET det
Familie NOUN nsubj
have VERB aux
-- PUNCT punct
og CCONJ cc
saa ADV advmod
dø ADJ conj
, PUNCT punct

 SPACE
tilbyde VERB ccomp
hun PRON nsubj
at PART mark
tag VERB obj
jeg PRON obj
til ADP case
sig PRON obl
og CCONJ cc
opdrage VERB conj
jeg PRON obj
, PUNCT punct
bare ADV advmod
for ADP case
at PART mark
ærgre VERB obj

 SPACE
Mama PROPN obj
, PUNCT punct
fortælle VERB ROOT
hun PRON nsubj
jeg PRON obj
ofte ADV advmod
. PUNCT punct
Da SCONJ mark
jeg PRON nsubj
kun ADV advmod
være AUX cop
fire NUM nummod
Aar NOUN obl
, PUNCT punct
have AUX ROOT
jeg PRON nsubj
ikke ADV advmod

 SPACE
nogen PRON obj
at PART mark
sige VERB acl:relcl
i ADP case
den DET det
Sag NOUN obl
, PUNCT punct
og CCONJ cc
hvis SCONJ mark
Mama PROPN nsubj
have VERB dep
Lyst NOUN obj
til ADP mark
at PART mark
give VERB advcl
Afkald NOUN obj

 SPACE
paa ADP case
jeg PRON obl
, PUNCT punct
blive AUX cop
det PRON nsubj
jo ADV advmod
hendes DET det
Sag NOUN conj
. PUNCT punct
Mamas PROPN nmod:poss
Fader NOUN nsubj
være AUX cop
Lord PROPN ROOT
og CCONJ dep
hendes DET det
Moder NOUN conj

 SPACE
jeg PRON nsubj
véd VERB ROOT
ikke ADV advmod
hvem PRON obj
, PUNCT punct
og CCONJ cc
de PRON nsubj
have AUX aux
ikke ADV advmod
gøre VERB conj
sig PRON iobj
den DET det
Ulejlighed NOUN obj
at PART mark
blive AUX cop

 SPACE
gift VERB nmod
, PUNCT punct
det PRON nsubj
være AUX cop
derfor ADV advmod
, PUNCT punct
at SCONJ mark
stakkels ADJ acl:relcl
Mama PROPN flat
slette ADV advmod
ingen DET det
Slægtninge NOUN nsubj
have VERB acl:relcl
. PUNCT punct

 SPACE
Da SCONJ mark
Papa PROPN nsubj
være AUX cop
dø ADJ advmod
, PUNCT punct
gifte VERB ROOT
hun PRON nsubj
sig PRON obj
mede ADP case
en DET det
Officer NOUN obl
og CCONJ cc
rejse VERB conj
til ADP case
Indien PROPN obl

 SPACE
og CCONJ cc
dø ADJ conj
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
saá VERB conj
hun PRON nsubj
aldrig ADV advmod
mere ADV advmod
-- PUNCT punct
og CCONJ cc
saadan ADV advmod
gaar VERB conj
det PRON nsubj
til ADP mark
, PUNCT punct
at SCONJ mark

 SPACE
der PRON expl
ikke ADV advmod
være AUX advcl
en DET det
Sjæl NOUN obj
i ADP case
Verden NOUN obl
, PUNCT punct
som PRON nsubj
komme VERB acl:relcl
jeg PRON obj
vide ADP mark
, PUNCT punct
eller CCONJ cc
som ADP mark

 SPACE
interessere VERB conj
sig PRON obj
for ADP case
jeg PRON obl
, PUNCT punct
saa SCONJ mark
jeg PRON nsubj
kunne AUX aux
ikke ADV advmod
gøre VERB advmod
for ADP case
, PUNCT punct
at SCONJ mark
jeg PRON nsubj
være AUX cop
en DET det

 SPACE
Eventyrerske NOUN flat
og CCONJ cc
kun ADV advmod
tænke VERB conj
paa ADP advmod
jeg PRON obl
selv PRON nmod
, PUNCT punct
kunne AUX conj
jeg PRON nsubj
vel ADV advmod
? PUNCT punct


 SPACE
Fru PROPN nsubj
Carruthers PROPN flat
være VERB cop
til ADP case
Tider NOUN nmod
Uvenner NOUN ROOT
mede ADP case
alle ADJ amod
Naboerne NOUN nmod
, PUNCT punct
saa SCONJ advmod
naar ADV obl

 SPACE
undtage VERB ccomp
nogen DET det
formel ADJ amod
Visitter NOUN nsubj
i ADP case
de DET det
venskabelig ADJ amod
Mellemrum NOUN obl
, PUNCT punct
saá VERB ROOT
vi PRON nsubj

 SPACE
ikke ADV advmod
megen ADJ obj
til ADP case
de PRON obl
. PUNCT punct
Der ADV expl
være VERB ROOT
flere ADJ amod
gammel ADJ amod
Verdensdamer NOUN obj
, PUNCT punct
som PRON nsubj
pleje VERB acl:relcl
at PART mark

 SPACE
komme VERB obj
og CCONJ cc
besøge VERB conj
vi PRON obj
, PUNCT punct
men CCONJ cc
jeg PRON nsubj
kunde NOUN advmod
ikke ADV advmod
lide VERB conj
nogen PRON obj
af ADP case
de PRON obl
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
have VERB conj

 SPACE
ingen DET det
unge ADJ amod
Veninder NOUN obj
. PUNCT punct
Naar ADV mark
det PRON nsubj
blive AUX cop
mørk ADJ amod
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
være AUX cop
alene ADV advmod
her ADV conj
oppe ADV advmod
, PUNCT punct

 SPACE
spekulere VERB ROOT
jeg PRON nsubj
ofte ADV advmod
paa ADP advmod
, PUNCT punct
hvorledes ADV mark
det DET det
vild ADJ nsubj
hav AUX aux
være VERB xcomp
, PUNCT punct
hvis SCONJ mark
jeg PRON nsubj

 SPACE
have AUX aux
have VERB ccomp
nogen PRON obj
-- PUNCT punct
men CCONJ cc
jeg PRON nsubj
tro VERB conj
, PUNCT punct
at SCONJ mark
jeg PRON nsubj
være VERB obj
af ADP case
den DET det
Slags NOUN obl
Katte NOUN nmod
, PUNCT punct
som PRON dep

 SPACE
ikke ADV advmod
vild ADJ advmod
hav AUX aux
komme VERB acl:relcl
videre ADV advmod
godte ADV advmod
ud ADV obl:loc
af ADP case
det PRON obl
mede ADP case
de PRON obl
-- PUNCT punct
saa SCONJ mark
det PRON nsubj
være AUX cop

 SPACE
maaske ADV advmod
god ADJ amod
saaledes ADV dep
, PUNCT punct
hvis SCONJ mark
jeg PRON nsubj
bare ADV advmod
have VERB advmod
-- PUNCT punct
for ADP case
Eksempel NOUN nmod
en DET det
smuk ADJ amod

 SPACE
Tante NOUN obj
til ADP mark
at PART mark
holde VERB advcl
af ADP case
jeg PRON obl
, PUNCT punct
det DET det
kunde NOUN nsubj
hav AUX aux
være AUX cop
rar ADJ amod
. PUNCT punct


 SPACE
Fru PROPN nsubj
Carruthers PROPN flat
have VERB ROOT
ingen PRON obj
af ADP case
den DET det
Slags NOUN nmod
Følelser NOUN nmod
. PUNCT punct
" PUNCT punct
Snak VERB ROOT
og CCONJ cc
Vrøvl ADV conj
" PUNCT punct
-- PUNCT punct

 SPACE
" PUNCT punct
sentimental ADV amod
Pjank PROPN ROOT
" PUNCT punct
vild ADJ amod
hun PRON nsubj
hav AUX aux
kalde VERB acl:relcl
de PRON obj
. PUNCT punct
At PART mark
faa VERB ccomp
en DET det
passe ADJ amod

 SPACE
Mand NOUN obj
, PUNCT punct
det PRON nsubj
være AUX cop
det PRON conj
, PUNCT punct
hun PRON nsubj
have AUX aux
opdrag VERB acl:relcl
jeg PRON obj
til ADP mark
, PUNCT punct
sige VERB ROOT
hun PRON nsubj
, PUNCT punct
og CCONJ cc
i ADP case
de PRON det

 SPACE
sidste ADJ amod
Aar NOUN obl
have AUX aux
hun PRON nsubj
arrangere VERB conj
, PUNCT punct
at SCONJ mark
jeg PRON nsubj
skulde AUX aux
gift VERB obj
mede ADP case
hendes DET det

 SPACE
forhadt ADJ amod
Arving NOUN obl
, PUNCT punct
da SCONJ mark
jeg PRON nsubj
skulde AUX aux
hav VERB advmod
Pengene NOUN obj
og CCONJ cc
han PRON conj
Godset NOUN flat
. PUNCT punct


 SPACE
Han PRON nsubj
være AUX cop
Diplomat NOUN ROOT
og CCONJ cc
bo VERB conj
i ADP case
Paris PROPN obl
og CCONJ cc
Rusland PROPN conj
og CCONJ cc
den DET det
Slags NOUN conj
morsom ADJ amod

 SPACE
Steder NOUN nmod
, PUNCT punct
saa SCONJ mark
han PRON nsubj
komme VERB conj
sjælden ADJ amod
til ADP case
England PROPN obl
. PUNCT punct
Jeg PRON nsubj
have AUX aux
aldrig ADV advmod
se VERB ROOT
han PRON obj
. PUNCT punct

 SPACE
Han PRON nsubj
være AUX cop
helt ADV advmod
gammel ADJ ROOT
-- PUNCT punct
over ADP case
tredive NUM obl
-- PUNCT punct
og CCONJ cc
hans DET det
Haar NOUN nsubj
begynde VERB conj
at PART mark
blive AUX cop

 SPACE
graat NOUN obj
. PUNCT punct


 SPACE
Nu ADV advmod
være AUX cop
han PRON nsubj
Herre NOUN ROOT
her ADV advmod
, PUNCT punct
og CCONJ cc
jeg PRON nsubj
være AUX cop
nødt ADJ conj
til ADP mark
at PART mark
rejse VERB acl:relcl
herfra ADV advmod
-- PUNCT punct
hvis SCONJ mark
han PRON nsubj

 SPACE
ikke ADV advmod
fri VERB advmod
til ADP case
jeg PRON nmod
i ADP case
Eftermiddag NOUN nmod
, PUNCT punct
naar SCONJ mark
vi PRON nsubj
møde VERB advmod
, PUNCT punct
hvilken PRON mark
han PRON nsubj

 SPACE
sandsynligvis ADV advmod
ikke ADV advmod
gø VERB acl:relcl
. PUNCT punct


 SPACE
For ADP case
Resten NOUN obl
kunne VERB aux
der ADV nsubj
da ADV advmod
ikke ADV advmod
være AUX cop
nogen DET det
ond ADV ROOT
i ADP mark
, PUNCT punct
at SCONJ mark
jeg PRON nsubj
unde ADP case
de DET det

 SPACE
Omstændigheder NOUN obl
gø VERB acl:relcl
jeg PRON iobj
Umage NOUN obj
for ADP mark
at PART mark
se VERB advcl
saa ADV obj
tiltale ADJ amod
ud ADV advmod
som ADP case
mulig ADJ obl
. PUNCT punct

 SPACE
Siden SCONJ mark
jeg PRON nsubj
skulle AUX aux
være AUX cop
Eventyrerske NOUN advmod
, PUNCT punct
maa AUX aux
jeg PRON nsubj
gøre VERB ROOT
det DET det
god ADJ obj
, PUNCT punct
jeg PRON nsubj
kunne VERB acl:relcl
, PUNCT punct

 SPACE
for ADP case
jeg PRON obl
selv PRON nmod
. PUNCT punct
Fine ADJ nmod:poss
Følelser NOUN nsubj
passe VERB ROOT
for ADP case
Folk NOUN obl
, PUNCT punct
der PRON nsubj
have VERB acl:relcl
Penge NOUN obj
nok ADV advmod
til ADP mark
at PART mark

 SPACE
leve VERB advcl
som ADP mark
de PRON nsubj
have VERB advcl
Lyst NOUN obj
. PUNCT punct
Hvis SCONJ mark
jeg PRON nsubj
have AUX ROOT
tie NUM nummod
Tusind NOUN obj
om ADP case
Aaret NOUN nmod
, PUNCT punct
eller CCONJ dep
blotte ADV advmod

 SPACE
fem NUM dep
, PUNCT punct
saa ADV advmod
vild ADJ conj
jeg PRON nsubj
knipse VERB acl:relcl
mede ADP case
Fingrene NOUN obl
ad ADP case
alle ADJ amod
Mænd NOUN nmod
og CCONJ cc
sige VERB conj
: PUNCT punct
" PUNCT punct
Nej INTJ ROOT
, PUNCT punct

 SPACE
jeg PRON nsubj
leve VERB ROOT
min DET det
Liv NOUN obj
som ADP obj
jeg PRON nsubj
ville VERB acl:relcl
, PUNCT punct
jeg PRON nsubj
ville AUX aux
udvide VERB conj
min DET det
Kundskaber NOUN obj
og CCONJ cc
læse VERB conj

 SPACE
Bøger NOUN obj
og CCONJ cc
hav VERB conj
smuk ADJ amod
Ideer NOUN obj
om ADP case
Ære NOUN nmod
og CCONJ cc
ophøje ADJ conj
Følelser NOUN conj
, PUNCT punct
og CCONJ cc
maaske ADV nsubj

 SPACE
engang ADV advmod
buk VERB conj
unde ADV compound:prt
for ADP case
en DET det
ædel ADJ amod
Kærlighed NOUN obl
" PUNCT punct
( PUNCT punct
hvilken PRON mark
stor ADJ amod
Ord NOUN nmod
, PUNCT punct
alene ADV advmod

 SPACE
Tanken NOUN obj
om ADP mark
det PRON nsubj
faar VERB advcl
jeg PRON obj
til ADP mark
at PART mark
skrive VERB advcl
) PUNCT punct
. PUNCT punct
Men CCONJ cc
hvis SCONJ mark
Hr. PROPN nsubj
Carruthers PROPN flat
nu ADV advmod

 SPACE
spørge VERB dep
jeg PRON obj
, PUNCT punct
om SCONJ mark
jeg PRON nsubj
ville AUX aux
gift VERB advmod
jeg PRON obj
mede ADP case
han PRON obl
, PUNCT punct
som PRON obj
hans DET det
Tante NOUN nsubj
have AUX aux
sige VERB acl:relcl
, PUNCT punct

 SPACE
at SCONJ mark
han PRON nsubj
skulle VERB advmod
, PUNCT punct
saa ADV advmod
sige VERB ROOT
jeg PRON nsubj
sikker ADV advmod
Ja INTJ obj
og CCONJ cc
blive AUX cop
her ADV conj
og CCONJ cc
faar VERB conj
en DET det

 SPACE
behagelig ADJ amod
Hjem NOUN obj
. PUNCT punct
Det PRON nsubj
være AUX cop
ikke ADV advmod
Umagen NOUN advmod
værd ADJ ROOT
at PART mark
begynde VERB acl:relcl
at PART mark
pakke VERB obj
ind ADV advmod
, PUNCT punct
føre SCONJ mark

 SPACE
jeg PRON nsubj
have AUX aux
træffe VERB acl:relcl
han PRON obj
. PUNCT punct


 SPACE
Hvor ADV advmod
det PRON nsubj
være AUX cop
heldig ADJ ROOT
, PUNCT punct
at SCONJ mark
Sort ADJ nsubj
klæde VERB advcl
jeg PRON obj
! PUNCT punct
Min DET det
Hud NOUN nsubj
være AUX cop
latterlig ADJ advmod
hvid ADJ ROOT
. PUNCT punct

 SPACE
Jeg PRON nsubj
ville AUX aux
sætte VERB ccomp
en DET det
Buket NOUN nmod
Violer NOUN obj
i ADP case
Brystet NOUN obl
paa ADP case
min DET det
Kjole NOUN obl
, PUNCT punct
det PRON nsubj
kunne AUX aux
da ADV mark

 SPACE
ikke ADV advmod
se VERB ccomp
hjerteløs ADJ amod
ud ADV obl:loc
, PUNCT punct
antage VERB ROOT
jeg PRON nsubj
. PUNCT punct
Men CCONJ cc
hvis SCONJ mark
han PRON nsubj
spørge VERB dep
jeg PRON obj
, PUNCT punct
om SCONJ mark
jeg PRON nsubj

 SPACE
være AUX aux
bedrøve ADJ ROOT
over ADP case
Fru PROPN nmod:poss
Carruthers PROPN flat
Død PROPN obl
, PUNCT punct
saa ADV advmod
kunne AUX aux
jeg PRON nsubj
ikke ADV advmod
lyve VERB conj
. PUNCT punct


 SPACE
Jeg PRON nsubj
være AUX aux
naturligvis ADV advmod
bedrøve ADJ ROOT
, PUNCT punct
fordi SCONJ mark
Døden NOUN nsubj
være AUX cop
frygtelig ADJ amod
, PUNCT punct
og CCONJ cc
at PART mark
dø VERB conj
paa ADP advmod

 SPACE
den DET det
Maade NOUN obj
, PUNCT punct
medens SCONJ mark
man PRON nsubj
sige VERB advmod
ondskabsfuld ADJ amod
Ting NOUN obj
til ADP case
alle ADJ obl
, PUNCT punct
det PRON nsubj
maa AUX aux
være AUX cop

 SPACE
rædsom ADJ advmod
-- PUNCT punct
men CCONJ cc
jeg PRON nsubj
kunne AUX conj
ikke ADV advmod
, PUNCT punct
jeg PRON nsubj
kunne AUX aux
ikke ADV advmod
begræde VERB ccomp
hun PRON obj
! PUNCT punct
Der ADV expl
gå VERB ROOT

 SPACE
aldrig ADV advmod
en DET det
Dag NOUN obj
, PUNCT punct
uden ADP mark
at SCONJ mark
hun PRON nsubj
saarede VERB advcl
jeg PRON obj
-- PUNCT punct
da SCONJ mark
jeg PRON nsubj
være AUX cop
lille ADJ amod
, PUNCT punct
være AUX cop
det PRON nsubj

 SPACE
ikke ADV advmod
blotte ADV advmod
mede ADP case
Ord NOUN nmod
; PUNCT punct
hun PRON nsubj
pleje VERB acl:relcl
at PART mark
knibe VERB obj
jeg PRON obj
og CCONJ cc
slaa VERB conj
jeg PRON obj
paa ADP case
Ørene NOUN obl
, PUNCT punct

 SPACE
til ADP case
Doktor NOUN obl
Garrison PROPN flat
sige VERB conj
, PUNCT punct
at SCONJ mark
jeg PRON nsubj
kunde NOUN nsubj
blive AUX cop
døve ADJ ccomp
, PUNCT punct
saa ADV advmod
holdt VERB conj
hun PRON nsubj
oppe ADV obl:loc
, PUNCT punct

 SPACE
for CCONJ case
hun PRON nsubj
sige VERB advcl
, PUNCT punct
at SCONJ mark
døve ADJ amod
Mennesker NOUN nsubj
være AUX cop
en DET det
Plage NOUN ccomp
, PUNCT punct
og CCONJ dep
hun PRON nsubj
kunde NOUN conj
ikke ADV advmod

 SPACE
holde VERB acl:relcl
de PRON obj
ud ADV compound:prt
. PUNCT punct


 SPACE
Jeg PRON nsubj
ville AUX aux
ikke ADV advmod
blive AUX cop
vide ADV ROOT
mede ADP mark
at PART mark
se VERB advcl
tilbage ADV obl:loc
, PUNCT punct
der PRON expl
være VERB acl:relcl
Masser NOUN obj
af ADP case
Ting NOUN nmod
, PUNCT punct
som PRON nsubj

 SPACE
jeg PRON acl:relcl
selv PRON obl
nu ADV advmod
blive AUX dep
rase ADJ amod
vide ADP mark
at PART mark
tænke VERB advcl
paa ADP advmod
. PUNCT punct


 SPACE
Jeg PRON nsubj
have AUX aux
kun ADV advmod
deltage VERB ROOT
i ADP case
Selskabslivet NOUN obl
i ADP case
en DET det
Aar NOUN obl
. PUNCT punct
Fru PROPN nsubj
Carruthers PROPN flat
få VERB ROOT
en DET det

 SPACE
Anfald NOUN obj
af ADP case
Bronkitis PROPN nmod
, PUNCT punct
da SCONJ mark
jeg PRON nsubj
være AUX cop
atten NOUN nsubj
Aar NOUN advmod

## Practicing with the example text
When working with languages that have inflection, we typically use `token.lemma_` instead of `token.text` like you'll find in the English examples. This is important when we're counting, so that differently-inflected forms of a word (e.g. masculine vs. feminine or singular vs. plural) aren't counted as if they were different words.

In [12]:
filepath = "../texts/da.txt"
document = nlp(open(filepath, encoding="utf-8").read())

## Get Adjectives

| POS   | Description               | Examples                                      |
|:-----:|:-------------------------:|:---------------------------------------------:|
| ADJ   | adjective                 | big, old, green, incomprehensible, first      |

To extract and count the adjectives in the example text, we will follow the same model as above, except we'll add an `if` statement that will pull out words only if their POS label matches "ADJ."

:::{admonition} Python Review
:class: pythonreview

While we demonstrate how to extract parts of speech in the sections below, we're also going to reinforce some integral Python skills. Notice how we use `for` loops and `if` statements to `.append()` specific words to a list. Then we count the words in the list and make a pandas dataframe from the list.
:::

Here we make a list of the adjectives identified in the example text:

In [15]:
adjs = []
for token in document:
    if token.pos_ == 'ADJ':
        adjs.append(token.lemma_)

In [16]:
adjs

['NY',
 '3.',
 'vild',
 'morsom',
 'alt',
 'mulig',
 'godte',
 'inkonsekvent',
 'ordentlig',
 'alt',
 'forrige',
 'syg',
 'samme',
 'behagelig',
 'godte',
 'dø',
 'virkelig',
 'meste',
 'umulig',
 'eg',
 'stakkels',
 'dø',
 'stakkels',
 'dø',
 'dø',
 'alle',
 'formel',
 'venskabelig',
 'megen',
 'flere',
 'gammel',
 'unge',
 'mørk',
 'vild',
 'vild',
 'god',
 'smuk',
 'rar',
 'vild',
 'passe',
 'sidste',
 'forhadt',
 'morsom',
 'sjælden',
 'gammel',
 'nødt',
 'tiltale',
 'mulig',
 'god',
 'Fine',
 'vild',
 'alle',
 'smuk',
 'ophøje',
 'ædel',
 'stor',
 'behagelig',
 'værd',
 'heldig',
 'Sort',
 'latterlig',
 'hvid',
 'hjerteløs',
 'bedrøve',
 'bedrøve',
 'frygtelig',
 'ondskabsfuld',
 'alle',
 'rædsom',
 'lille',
 'døve',
 'døve',
 'rase',
 'rask',
 'vild',
 'næste',
 'sidste',
 'dø',
 'Vrede',
 'gammel',
 'rig',
 'unyttig',
 'alt',
 'tilstrækkelig',
 'grim',
 'kedelig',
 'nervepirrende',
 'gift',
 'megen',
 'gammel',
 'ækel',
 'Fyre',
 'fleste',
 'fæl',
 'lille',
 'trave',
 'underlig',
 'vi',
 'underlig',
 'sidste',
 'ung',
 'menneskelig',
 'alle',
 'lidt',
 'hov',
 'unge',
 'gift',
 'kedelig',
 'gift',
 'alle',
 'gift',
 'dejlig',
 'megen',
 'unødvendig',
 'nødt',
 'vild',
 'god',
 'solid',
 'gift',
 'ækel',
 'vild',
 'alle',
 'underlig',
 'rødt',
 'mørk',
 'sædvanlig',
 'hvide',
 'vild',
 'ren',
 'grim',
 'sort',
 'tyk',
 'megen',
 'hele',
 'alle',
 'vild',
 'vild',
 'mulig',
 'Gode',
 'unge',
 'megen',
 'grøn',
 'lyse',
 'lange',
 'god',
 'gift',
 'Alt',
 'høflig',
 'gift',
 'alt',
 'ovenpaa',
 'virkningsfuld',
 'lange',
 'sort',
 'stor',
 'brede',
 'pragtfuld',
 'smuk',
 'nervøs',
 'bestandig',
 'samme',
 'Tantes',
 'gammel',
 'klar',
 'ny',
 'sort',
 'stærk',
 'rigtig',
 'høj',
 'glatraget',
 'firkantet',
 'megen',
 'destingveret',
 'kold',
 'arrogant',
 'bedaarende',
 'forfine',
 'gammel',
 'stor',
 'egn',
 'gammel',
 'hele',
 'vild',
 'vild',
 'utiltalende',
 'megen',
 'kedelig',
 'indre',
 'tiltale',
 'vild',
 'ærbar',
 'afskyelig',
 'ægte',
 'engelsk',
 'love',
 'samme',
 'banal',
 'vild',
 'kejtet',
 'vild',
 'færdig',
 'kold',
 'hele',
 'kejtet',
 'kedelig',
 'simpel',
 'mørk',
 'vild',
 'sædvanlig',
 'ringeagte',
 'færdig',
 'Ønske',
 'kedelig',
 'Fremmed',
 'mulig',
 'stille',
 'vild',
 'dristig',
 'sikker',
 'enig',
 'umulig',
 'enig',
 'oprigtigste',
 'vant',
 'virkelig',
 'Vrede',
 'glad',
 'ren',
 'le',
 'færdig',
 'samme',
 'vild',
 'mere',
 'stiv',
 'vred',
 'enig',
 'mere',
 'rase',
 'vride',
 'ufølsom',
 'eneste',
 'fattig',
 'grøn',
 'rødt',
 'stærk',
 'mere',
 'rolig',
 'mere',
 'mangen',
 'alle',
 'skamfuld',
 'vild',
 'rase',
 'red',
 'rimelig',
 'voldsom',
 'klare',
 'uberegnelig',
 'ung',
 'taabelig',
 'flere',
 'arrogant',
 'al',
 'juridisk',
 'rolig',
 'vild',
 'latterlig',
 'sand',
 'kold',
 'forbitre',
 'samme',
 'rase',
 'alle',
 'forskellig',
 'stor',
 'godte',
 'villig',
 'elskværdig',
 'mulig',
 'rædsom',
 'fritte',
 'lykkelig',
 'Bedste',
 'daarligt',
 'ubehagelig',
 'smuk',
 'fløjlsblød',
 'forlegen',
 'mangen',
 'sand',
 'høflig',
 'nær',
 'alt',
 'ung',
 'alle',
 'megen',
 'Døde',
 'ærgerlig',
 'dristig',
 'sort',
 'behagelig',
 'sælsom',
 'lille',
 'spidse',
 'god',
 'vild',
 'ung',
 'underlig',
 'mangen',
 'særlig',
 'sidste',
 'pæn',
 'flere',
 'umulig',
 'ung',
 'ansvarlig',
 'vild',
 'huslig',
 'vild',
 'megen',
 'sikker',
 'god',
 'besværlig',
 'lille',
 'oprigtig',
 'samme',
 'mangen',
 'sædvanlig',
 'ny',
 'lille',
 'værdige',
 'alvorlig',
 'frejdig',
 'nervøs',
 'stor',
 'dumme',
 'nøjagtig',
 'smuk',
 'smigre',
 'god',
 'haabede',
 'sympatisk',
 'umiddelbar',
 'hele',
 'hele',
 'rolig',
 'mere',
 'god',
 'god',
 'le',
 'stor',
 'komisk',
 'besynderligste',
 'megen',
 'mulig',
 'stor',
 'pragtfuld',
 'svær',
 'gammel',
 'italiensk',
 'stive',
 'purpurrød',
 'halv',
 'først',
 'rigtig',
 'gammel',
 'vild',
 'smuk',
 'vild',
 'megen',
 'lille',
 'vild',
 'vild',
 'gift',
 'megen',
 'samme',
 'urolig',
 'gal',
 'underlig',
 'beruse',
 'alt',
 'stive',
 'alt',
 'dejlig',
 'sikker',
 'tilstrækkelig',
 'god',
 '3.',
 'Kære',
 'sælsom',
 'vild',
 'rødt',
 'grøn',
 'sort',
 'uudtalt',
 'gode',
 'sjælden',
 'rød',
 'samme',
 'ren',
 'enestaaende',
 'gammel',
 'eneste',
 'først',
 'gammel',
 'fin',
 'god',
 '4.',
 'stor',
 'venlig',
 'ligegyldig',
 'foregaaende',
 'ubehagelig',
 'alle',
 'forskellig',
 'alt',
 'latterlig',
 'afskyelig',
 'hele',
 'alt',
 'vild',
 'elskværdig',
 'uelskværdig',
 'stor',
 'gode',
 'halv',
 'foregaaende',
 'alt',
 'mulig',
 'haarde',
 'kede',
 'bestemt',
 'først',
 'menneskelig',
 'behagelig',
 'tørre',
 'pludselig',
 'vrede',
 'flere',
 'hyggelig',
 'stor',
 'gode',
 'utaalmodig',
 'nødvendig',
 'kedelig',
 'vild',
 'godte',
 'dum',
 'rar',
 'nydelig',
 'hyggelig',
 'meningsløs',
 'pludselig',
 'vaad',
 'trist',
 'alvorlig',
 'red',
 'ny',
 'vild',
 'mulig',
 'klar',
 'umulig',
 'anderledes',
 'ensom',
 'umulig',
 'gal',
 'dejlig',
 'vild',
 'megen',
 'kedelig',
 'smuk',
 'sikker',
 'lille',
 'gift',
 'samme',
 'rigtig',
 'enig',
 'vild',
 'først',
 'vild',
 'stærk',
 'Gamle',
 'sidste',
 'gammel',
 'gode',
 'vild',
 'vild',
 'fjolle',
 'undselig',
 'underlig',
 'gammel',
 'nydelig',
 'god',
 'vild',
 'rød',
 'nødt',
 'vride',
 'forbitre',
 'megen',
 'tosse',
 'gammel',
 'visse',
 'farve',
 'vild',
 'samme',
 'underlig',
 'lille',
 'vild',
 'alt',
 'alt',
 'stor',
 'hvide',
 'le',
 'stakkels',
 'gammel',
 'vild',
 'ensom',
 'god',
 'ærgerlig',
 'kede',
 'færdig',
 'hvide',
 'mere',
 'kunstig',
 'indtage',
 'belvederiske',
 'smal',
 'smuk',
 'smidig',
 'stor',
 'søvnig',
 'blaa',
 'lille',
 'bitte',
 'smuk',
 'hele',
 'smuk',
 'vild',
 'kynisk',
 'haarde',
 'vi',
 'gammel',
 'mere',
 'rolig',
 'venskabeligste',
 'banal',
 'hele',
 'umaadeligt',
 'gammel',
 'vi',
 'vild',
 'upassende',
 'færdig',
 'gammel',
 'høflig',
 'stive',
 'yndig',
 'nydelig',
 'sort',
 'tynde',
 'tækkelig',
 'klædelig',
 'vild',
 'skikkelig',
 'alle',
 'balstyrig',
 'raadeligt',
 'god',
 'høj',
 'megen',
 'høj',
 'stive',
 'stramme',
 'udsøge',
 'megen',
 'køn',
 'morsom',
 'optage',
 'gammel',
 'lange',
 'pæn',
 'ærbareste',
 'sikker',
 'vild',
 'god',
 'stor',
 'interessant',
 'hele',
 'elektrisk',
 'Lys',
 'bestemt',
 'fløjlsblød',
 'vanskelig',
 'kede',
 'vild',
 'ren',
 'vild',
 'blaa',
 'bønlig',
 'røre',
 'bedrøve',
 'umulig',
 'gammel',
 'vidunderlig',
 'alle',
 'søsyge',
 'menneskelig',
 'Alle',
 'alle',
 'gammel',
 'skaldet',
 'glad',
 'vild',
 'samme',
 'megen',
 'dejlig',
 'smuk',
 'elskværdig',
 'dumme',
 'bekvem',
 'Fløjls',
 'purpurrød',
 'Fløjls',
 'gode',
 'gammel',
 'stor',
 'rædsom',
 'vi',
 'italiensk',
 'tredie',
 'vild',
 'godte',
 'ansvarlig',
 'respektabel',
 'italiensk',
 'alt',
 'Fløjls',
 'godte',
 'hele',
 'skarp',
 'fin',
 'vild',
 'vild',
 'lange',
 'blanke',
 'stor',
 'paatagen',
 'iskold',
 'stiv',
 'stateligste',
 'smuk',
 'bone',
 'stille',
 'kynisk',
 'trætte',
 'hele',
 'alt',
 'interessant',
 'tvetydig',
 'uholdbar',
 'megen',
 'dum',
 'tosse',
 'rød',
 '5.',
 'femte',
 'vild',
 'spartansk',
 'hele',
 'Kære',
 'kedelig',
 'hengive',
 'sikker',
 'Velkommen',
 'fortabe',
 'alle',
 'søde',
 'vi',
 'henrykt',
 'ung',
 'rar',
 'fleste',
 'gammel',
 'god',
 'lille',
 'alt',
 'uskyldig',
 'munter',
 'elskværdig',
 'glad',
 'færdig',
 'færdig',
 'stive',
 'uheldig',
 'saadant',
 'samme',
 'vild',
 'passe',
 'al',
 'demoiselle',
 'monde',
 'vride',
 'sand',
 'øjensynlig',
 'rig',
 'sikker',
 'megen',
 'mangen',
 'hellig',
 'hele',
 'Stakkels',
 'gammel',
 'stor',
 'varme',
 'kold',
 'ømme',
 'moderlig',
 'alle',
 'allerværst',
 'dejlig',
 'samme',
 'behagelig',
 'søvnig',
 'blaa',
 'lange',
 'vi',
 'vild',
 'al',
 'god',
 'færdig',
 'Kære',
 'taabelige',
 'lille',
 'sikker',
 'mangen',
 'højtidelig',
 'smuk',
 'færdig',
 'ensom',
 'vild',
 'venlig',
 'udmærke',
 'upassende',
 'mulig',
 'bestandig',
 'forfærdelig',
 'gift',
 'alt',
 'morsom',
 'forunderlig',
 'lille',
 'megen',
 'alt',
 'grøn',
 'vild',
 'allerbedste',
 'unge',
 'megen',
 'vild',
 'ny',
 'alle',
 'rig',
 'vild',
 'alt',
 'nytte',
 'forskellig',
 'stor',
 'gode',
 'bedrøve',
 'katolsk',
 'snævre',
 'smuk',
 'rød',
 '9.',
 'hele',
 'røre',
 'kende',
 'flov',
 'bekvem',
 'kold',
 'vild',
 'mangen',
 'kedelig',
 'quart',
 'søde',
 'fremme',
 'glad',
 'insouciante',
 'sidste',
 'færdig',
 'lange',
 'fugtig',
 'friske',
 'vild',
 'ny',
 'ækel',
 'højrygget',
 'hjertelig',
 'rødt',
 'rødt',
 'grim',
 'rødt',
 'purpurrød',
 'ildrød',
 'bange',
 'mørk',
 'rig',
 'stakkels',
 'skønt',
 'skotsk',
 'plump',
 'gift',
 'voksen',
 'rødt',
 'glatte',
 'hvide',
 'venlig',
 'gode',
 'tredie',
 'fjerde',
 'veldædig',
 'alle',
 'mangen',
 'meste',
 'alle',
 'næste',
 'ældre',
 'vanskelig',
 'sidste',
 'sand',
 'helt',
 'hele',
 'diplomatisk',
 'alt',
 'lidt',
 'lange',
 'taktfuld',
 'vild',
 'mulig',
 'vild',
 'lille',
 'gammel',
 'uhyggelig',
 'forfærdelig',
 'ung',
 'ugift',
 'stor',
 'ugift',
 'frygtelig',
 'vild',
 'egn',
 'kære',
 'ugift',
 'egn',
 'venlig',
 'ugift',
 'næsvis',
 'gammel',
 'gift',
 'vild',
 'gammel',
 'vild',
 'vild',
 'klog',
 'egn',
 'vild',
 'fremme',
 'rædsom',
 'nydelig',
 'rosenrød',
 'gul',
 'tilfreds',
 'alle',
 'gammel',
 'skrækkelig',
 'flere',
 'vidunderlig',
 'halv',
 'god',
 'alle',
 'høj',
 'lille',
 'bitte',
 'høj',
 'tynde',
 'skrækkelig',
 'skotsk',
 'stor',
 'stærk',
 'solbrændt',
 'nøgen',
 'pragtfuld',
 'smuk',
 'Allé',
 'ærbødig',
 'glad',
 'først',
 'værst',
 'alle',
 'fremme',
 'nødt',
 'flink',
 'vild',
 'stadig',
 'nødt',
 'stille',
 'vant',
 'samme',
 'eneste',
 'megen',
 'vild',
 'alle',
 'urolig',
 'god',
 'bange',
 'alle',
 'mulig',
 'blaa',
 'frygtelig',
 'barbarisk',
 'flere',
 'rædsom',
 '9.',
 'nedtrykt',
 'vride',
 'mangen',
 'latterlig',
 'alle',
 'unge',
 'kende',
 'dum',
 'vild',
 'gode',
 'anderledes',
 'glad',
 'Alt',
 'vant',
 'gammel',
 'særlig',
 'eneste',
 'hele',
 'færdig',
 'sidste',
 'ny',
 'mangen',
 'galt',
 'smuk',
 'gift',
 'unge',
 'gift',
 'slem',
 'alle',
 'nødt',
 'kynisk',
 'morsom',
 'afhængig',
 'vild',
 'øvrig',
 'fri',
 'hele',
 'Montgomeriske',
 'alle',
 'selvstændig',
 'morsom',
 'høflig',
 'elskværdig',
 'tilfreds',
 'hvide',
 'forskellig',
 'korrekteste',
 'Slang',
 'hele',
 'solid',
 'fornuftig',
 'sædvanlig',
 'fornuftig',
 'dejlig',
 'skikkelig',
 'sædvanlig',
 'formel',
 'indbildsk',
 'lille',
 'alle',
 'galt',
 'slem',
 'alle',
 'naiv',
 'vild',
 'skotsk',
 'tidlig',
 'vild',
 'gammel',
 'dunkel',
 'dunkel',
 'rødt',
 'vild',
 'vild',
 'uhøflig',
 'venlig',
 'lille',
 ...]

Then we count the unique adjectives in this list with the `Counter()` module:

In [18]:
adjs_tally = Counter(adjs)

In [19]:
adjs_tally.most_common()

[('vild', 286),
 ('alle', 97),
 ('alt', 89),
 ('megen', 77),
 ('god', 70),
 ('gammel', 68),
 ('smuk', 63),
 ('stor', 61),
 ('lille', 61),
 ('hele', 60),
 ('gift', 35),
 ('glad', 31),
 ('mere', 31),
 ('samme', 29),
 ('sikker', 28),
 ('mangen', 27),
 ('søde', 27),
 ('mulig', 26),
 ('dejlig', 26),
 ('kedelig', 24),
 ('kold', 24),
 ('først', 24),
 ('høj', 23),
 ('bange', 23),
 ('sidste', 22),
 ('ung', 22),
 ('vride', 22),
 ('gode', 22),
 ('kære', 22),
 ('stakkels', 21),
 ('sand', 21),
 ('yndig', 21),
 ('eneste', 20),
 ('elskværdig', 20),
 ('lykkelig', 20),
 ('ulykkelig', 20),
 ('unge', 19),
 ('venlig', 19),
 ('eg', 18),
 ('nødt', 18),
 ('underlig', 18),
 ('godte', 17),
 ('umulig', 17),
 ('behagelig', 16),
 ('al', 16),
 ('slem', 16),
 ('sort', 15),
 ('færdig', 15),
 ('blaa', 15),
 ('morsom', 14),
 ('vi', 14),
 ('rødt', 14),
 ('lange', 14),
 ('rædsom', 13),
 ('frygtelig', 12),
 ('nervøs', 12),
 ('forskellig', 12),
 ('rød', 12),
 ('anderledes', 12),
 ('vidunderlig', 12),
 ('flere', 11),
 ('ny', 11),
 ('nydelig', 11),
 ('stærk', 10),
 ('halv', 10),
 ('Kære', 10),
 ('dum', 10),
 ('vanskelig', 10),
 ('forkøle', 10),
 ('Slangepige', 10),
 ('latterlig', 9),
 ('ren', 9),
 ('pragtfuld', 9),
 ('stille', 9),
 ('rolig', 9),
 ('dumme', 9),
 ('stive', 9),
 ('hyggelig', 9),
 ('indtage', 9),
 ('klog', 9),
 ('høflig', 8),
 ('rigtig', 8),
 ('egn', 8),
 ('ubehagelig', 8),
 ('ligegyldig', 8),
 ('trætte', 8),
 ('ene', 8),
 ('fuld', 8),
 ('grusom', 8),
 ('naturlig', 8),
 ('dø', 7),
 ('mørk', 7),
 ('rar', 7),
 ('passe', 7),
 ('ondskabsfuld', 7),
 ('rase', 7),
 ('næste', 7),
 ('rig', 7),
 ('menneskelig', 7),
 ('le', 7),
 ('alvorlig', 7),
 ('tredie', 7),
 ('kende', 7),
 ('fornærme', 7),
 ('værd', 6),
 ('bedrøve', 6),
 ('lidt', 6),
 ('sædvanlig', 6),
 ('hvide', 6),
 ('grøn', 6),
 ('Alt', 6),
 ('urolig', 6),
 ('fin', 6),
 ('kede', 6),
 ('bestemt', 6),
 ('ensom', 6),
 ('kynisk', 6),
 ('Stakkels', 6),
 ('forfærdelig', 6),
 ('ærbødig', 6),
 ('dyb', 6),
 ('egen', 6),
 ('kort', 6),
 ('kærlig', 6),
 ('blege', 6),
 ('svag', 6),
 ('vanvittig', 6),
 ('heldig', 5),
 ('Vrede', 5),
 ('enig', 5),
 ('fattig', 5),
 ('voldsom', 5),
 ('sælsom', 5),
 ('pæn', 5),
 ('gal', 5),
 ('nødvendig', 5),
 ('klædelig', 5),
 ('køn', 5),
 ('interessant', 5),
 ('elektrisk', 5),
 ('henrykt', 5),
 ('munter', 5),
 ('ældre', 5),
 ('ugift', 5),
 ('tilfreds', 5),
 ('fornuftig', 5),
 ('dunkel', 5),
 ('uhøflig', 5),
 ('gammeldags', 5),
 ('saadan', 5),
 ('kedsommelig', 5),
 ('fuldkommen', 5),
 ('guddommelig', 5),
 ('syg', 4),
 ('døve', 4),
 ('tilstrækkelig', 4),
 ('fleste', 4),
 ('bestandig', 4),
 ('bedaarende', 4),
 ('afskyelig', 4),
 ('vant', 4),
 ('stiv', 4),
 ('taabelig', 4),
 ('særlig', 4),
 ('komisk', 4),
 ('bitte', 4),
 ('Alle', 4),
 ('udmærke', 4),
 ('friske', 4),
 ('skrækkelig', 4),
 ('nedtrykt', 4),
 ('fri', 4),
 ('Vilde', 4),
 ("'", 4),
 ('løjerlig', 4),
 ('overlegen', 4),
 ('smaa', 4),
 ('ond', 4),
 ('lunefuld', 4),
 ('lav', 4),
 ('dagligdags', 4),
 ('gnave', 4),
 ('sød', 4),
 ('djævelsk', 4),
 ('statelig', 4),
 ('virkelig', 3),
 ('sjælden', 3),
 ('grim', 3),
 ('ækel', 3),
 ('solid', 3),
 ('arrogant', 3),
 ('engelsk', 3),
 ('kejtet', 3),
 ('simpel', 3),
 ('forbitre', 3),
 ('Bedste', 3),
 ('daarligt', 3),
 ('ærgerlig', 3),
 ('italiensk', 3),
 ('purpurrød', 3),
 ('haarde', 3),
 ('pludselig', 3),
 ('smidig', 3),
 ('upassende', 3),
 ('tynde', 3),
 ('røre', 3),
 ('Fløjls', 3),
 ('hengive', 3),
 ('uskyldig', 3),
 ('fremme', 3),
 ('skotsk', 3),
 ('glatte', 3),
 ('fjerde', 3),
 ('galt', 3),
 ('øvrig', 3),
 ('uartig', 3),
 ('flove', 3),
 ('fornemme', 3),
 ('rædselsfuld', 3),
 ('korte', 3),
 ('Tusind', 3),
 ('kær', 3),
 ('tiltrække', 3),
 ('éns', 3),
 ('Hele', 3),
 ('mandlig', 3),
 ('sørgelig', 3),
 ('mærkelig', 3),
 ('brune', 3),
 ('fortvivle', 3),
 ('almindelig', 3),
 ('lyserød', 3),
 ('knuse', 3),
 ('kæreste', 3),
 ('tarvelig', 3),
 ('syvende', 3),
 ('3.', 2),
 ('meste', 2),
 ('formel', 2),
 ('venskabelig', 2),
 ('tiltale', 2),
 ('hvid', 2),
 ('tyk', 2),
 ('Gode', 2),
 ('lyse', 2),
 ('klar', 2),
 ('forfine', 2),
 ('indre', 2),
 ('ægte', 2),
 ('banal', 2),
 ('Fremmed', 2),
 ('dristig', 2),
 ('ufølsom', 2),
 ('skamfuld', 2),
 ('red', 2),
 ('rimelig', 2),
 ('uberegnelig', 2),
 ('villig', 2),
 ('fløjlsblød', 2),
 ('ansvarlig', 2),
 ('huslig', 2),
 ('oprigtig', 2),
 ('svær', 2),
 ('foregaaende', 2),
 ('trist', 2),
 ('tosse', 2),
 ('farve', 2),
 ('søvnig', 2),
 ('venskabeligste', 2),
 ('skikkelig', 2),
 ('stramme', 2),
 ('optage', 2),
 ('Lys', 2),
 ('bekvem', 2),
 ('respektabel', 2),
 ('skarp', 2),
 ('uheldig', 2),
 ('øjensynlig', 2),
 ('varme', 2),
 ('nytte', 2),
 ('9.', 2),
 ('fugtig', 2),
 ('ildrød', 2),
 ('skønt', 2),
 ('voksen', 2),
 ('veldædig', 2),
 ('værst', 2),
 ('indbildsk', 2),
 ('naiv', 2),
 ('tidlig', 2),
 ('ydmyge', 2),
 ('dygtig', 2),
 ('kritisk', 2),
 ('rædsomste', 2),
 ('sørgmodig', 2),
 ('nysgerrig', 2),
 ('Nyt', 2),
 ('spænde', 2),
 ('gale', 2),
 ('Underbarnepige', 2),
 ('stolt', 2),
 ('hellige', 2),
 ('velopdragen', 2),
 ('mærkværdig', 2),
 ('hæs', 2),
 ('Klædningsstykke', 2),
 ('Kæreste', 2),
 ('ivrig', 2),
 ('muntre', 2),
 ('rødhaarede', 2),
 ('udtryksfuld', 2),
 ('bløde', 2),
 ('irritere', 2),
 ('mørke', 2),
 ('venetiansk', 2),
 ('ryggesløs', 2),
 ('nuværende', 2),
 ('forsigtig', 2),
 ('intelligent', 2),
 ('velskabt', 2),
 ('grov', 2),
 ('tunge', 2),
 ('ekstra', 2),
 ('rette', 2),
 ('hensynsfuld', 2),
 ('uforskammet', 2),
 ('rastløs', 2),
 ('elskelig', 2),
 ('taknemlig', 2),
 ('24.', 2),
 ('franske', 2),
 ('ubelejlig', 2),
 ('forrykt', 2),
 ('Vanære', 2),
 ('pukkelrygget', 2),
 ('fransk', 2),
 ('vigtig', 2),
 ('inderlig', 2),
 ('fortrylle', 2),
 ('vissen', 2),
 ('daarlig', 2),
 ('gylden', 2),
 ('hæderlig', 2),
 ('trofast', 2),
 ('Dele', 2),
 ('faa', 2),
 ('Zoologisk', 2),
 ('velkommen', 2),
 ('bitter', 2),
 ('varm', 2),
 ('moralsk', 2),
 ('fjerne', 2),
 ('tætte', 2),
 ('27.', 2),
 ('sige', 2),
 ('angstfuld', 2),
 ('lyksalig', 2),
 ('fordomsfuld', 2),
 ('modig', 2),
 ('prægtig', 2),
 ('uretfærdig', 2),
 ('elendig', 2),
 ('NY', 1),
 ('inkonsekvent', 1),
 ('ordentlig', 1),
 ('forrige', 1),
 ('forhadt', 1),
 ('Fine', 1),
 ('ophøje', 1),
 ('ædel', 1),
 ('Sort', 1),
 ('hjerteløs', 1),
 ('rask', 1),
 ('unyttig', 1),
 ('nervepirrende', 1),
 ('Fyre', 1),
 ('fæl', 1),
 ('trave', 1),
 ('hov', 1),
 ('unødvendig', 1),
 ('ovenpaa', 1),
 ('virkningsfuld', 1),
 ('brede', 1),
 ('Tantes', 1),
 ('glatraget', 1),
 ('firkantet', 1),
 ('destingveret', 1),
 ('utiltalende', 1),
 ('ærbar', 1),
 ('love', 1),
 ('ringeagte', 1),
 ('Ønske', 1),
 ('oprigtigste', 1),
 ('vred', 1),
 ('klare', 1),
 ('juridisk', 1),
 ('fritte', 1),
 ('forlegen', 1),
 ('nær', 1),
 ('Døde', 1),
 ('spidse', 1),
 ('besværlig', 1),
 ('værdige', 1),
 ('frejdig', 1),
 ('nøjagtig', 1),
 ('smigre', 1),
 ('haabede', 1),
 ('sympatisk', 1),
 ('umiddelbar', 1),
 ('besynderligste', 1),
 ('beruse', 1),
 ('uudtalt', 1),
 ('enestaaende', 1),
 ('4.', 1),
 ('uelskværdig', 1),
 ('tørre', 1),
 ('vrede', 1),
 ('utaalmodig', 1),
 ('meningsløs', 1),
 ('vaad', 1),
 ('Gamle', 1),
 ('fjolle', 1),
 ('undselig', 1),
 ('visse', 1),
 ('kunstig', 1),
 ('belvederiske', 1),
 ('smal', 1),
 ('umaadeligt', 1),
 ('tækkelig', 1),
 ('balstyrig', 1),
 ('raadeligt', 1),
 ('udsøge', 1),
 ('ærbareste', 1),
 ('bønlig', 1),
 ('søsyge', 1),
 ('skaldet', 1),
 ('blanke', 1),
 ('paatagen', 1),
 ('iskold', 1),
 ('stateligste', 1),
 ('bone', 1),
 ('tvetydig', 1),
 ('uholdbar', 1),
 ('5.', 1),
 ('femte', 1),
 ('spartansk', 1),
 ('Velkommen', 1),
 ('fortabe', 1),
 ('saadant', 1),
 ('demoiselle', 1),
 ('monde', 1),
 ('hellig', 1),
 ('ømme', 1),
 ('moderlig', 1),
 ('allerværst', 1),
 ('taabelige', 1),
 ('højtidelig', 1),
 ('forunderlig', 1),
 ('allerbedste', 1),
 ('katolsk', 1),
 ('snævre', 1),
 ('flov', 1),
 ('quart', 1),
 ('insouciante', 1),
 ('højrygget', 1),
 ('hjertelig', 1),
 ('plump', 1),
 ('helt', 1),
 ('diplomatisk', 1),
 ('taktfuld', 1),
 ('uhyggelig', 1),
 ('næsvis', 1),
 ('rosenrød', 1),
 ('gul', 1),
 ('solbrændt', 1),
 ('nøgen', 1),
 ('Allé', 1),
 ('flink', 1),
 ('stadig', 1),
 ('barbarisk', 1),
 ('afhængig', 1),
 ('Montgomeriske', 1),
 ('selvstændig', 1),
 ('korrekteste', 1),
 ('Slang', 1),
 ('fremmest', 1),
 ('ubeskyttet', 1),
 ('Eksempel', 1),
 ('ens', 1),
 ('mode', 1),
 ('utaalelige', 1),
 ('foroverbøjet', 1),
 ('lillebitte', 1),
 ('10.', 1),
 ('knappe', 1),
 ('brillant', 1),
 ('Forretningsbrev', 1),
 ('paastaaelig', 1),
 ('øse', 1),
 ('decidere', 1),
 ('flade', 1),
 ('enorm', 1),
 ('skraalende', 1),
 ('vissengule', 1),
 ('finte', 1),
 ('fordringsfuld', 1),
 ('snæver', 1),
 ('hurtig', 1),
 ('afdø', 1),
 ('besynderlig', 1),
 ('sømmelig', 1),
 ('fintfølende', 1),
 ('pinlig', 1),
 ('fornærmelig', 1),
 ('14.', 1),
 ('uendelig', 1),
 ('lumske', 1),
 ('praktisk', 1),
 ('uopdragen', 1),
 ('klæbrig', 1),
 ('forgæves', 1),
 ('lapset', 1),
 ('sær', 1),
 ('velgørende', 1),
 ('kristelig', 1),
 ('fikse', 1),
 ('fornøje', 1),
 ('ærlig', 1),
 ('forbavse', 1),
 ('dobbelt', 1),
 ('egenkærlig', 1),
 ('kluntet', 1),
 ('mørkebrun', 1),
 ('skygge', 1),
 ('gudelig', 1),
 ('afsides', 1),
 ('bekvemme', 1),
 ('ubesindig', 1),
 ('haardt', 1),
 ('usikker', 1),
 ('strid', 1),
 ('19.', 1),
 ('runde', 1),
 ('kvindelig', 1),
 ('ynkelig', 1),
 ('Een', 1),
 ('nærsynet', 1),
 ('Veste', 1),
 ('nyttig', 1),
 ('uregelmæssig', 1),
 ('pibe', 1),
 ('tynd', 1),
 ('farlig', 1),
 ('fabelagtig', 1),
 ('overflødig', 1),
 ('skadelig', 1),
 ('hæslig', 1),
 ('skønne', 1),
 ('tankefuld', 1),
 ('voks', 1),
 ('velklædt', 1),
 ('livlig', 1),
 ('galant', 1),
 ('skammelig', 1),
 ('23.', 1),
 ('øjeblikkelig', 1),
 ('oprindelig', 1),
 ('ransage', 1),
 ('vrøvl', 1),
 ('gerrig', 1),
 ('utaalelig', 1),
 ('allervigtigste', 1),
 ('bevidst', 1),
 ('plebejisk', 1),
 ('yndefuld', 1),
 ('forlade', 1),
 ('taktløs', 1),
 ('Hoste', 1),
 ('øllet', 1),
 ('fremtidig', 1),
 ('østrigsk', 1),
 ('arveløs', 1),
 ('henrive', 1),
 ('sorgløs', 1),
 ('rødhaaret', 1),
 ('EN', 1),
 ('blæse', 1),
 ('paaklædt', 1),
 ('Grev', 1),
 ('ualmindelig', 1),
 ('indeni', 1),
 ('Taabelige', 1),
 ('Arme', 1),
 ('oprøre', 1),
 ('Søde', 1),
 ('Stuepige', 1),
 ('lidenskabelig', 1),
 ('spansk', 1),
 ('højtravende', 1),
 ('persisk', 1),
 ('25.', 1),
 ('mage', 1),
 ('fortrædelig', 1),
 ('tilbøjelig', 1),
 ('urimelig', 1),
 ('lunke', 1),
 ('dyseptisk', 1),
 ('mellemst', 1),
 ('opmærksom', 1),
 ('Sidste', 1),
 ('følelsesløs', 1),
 ('velformet', 1),
 ('halvmørk', 1),
 ('brutal', 1),
 ('patetisk', 1),
 ('flygtig', 1),
 ('fornøjelig', 1),
 ('Syg', 1),
 ('Nødvendige', 1),
 ('Grønt', 1),
 ('godmodig', 1),
 ('troløs', 1),
 ('aparte', 1),
 ('fantastisk', 1),
 ('snavs', 1),
 ('Umuligt', 1),
 ('ekscentrisk', 1),
 ('ukonventionel', 1),
 ('trolove', 1),
 ('Frøken', 1),
 ('adsprede', 1),
 ('selvretfærdig', 1),
 ('forkert', 1),
 ('kvitte', 1),
 ('agtværdig', 1),
 ('ukendt', 1),
 ('26.', 1),
 ('mægtig', 1),
 ('stik', 1),
 ('modsætte', 1),
 ('blide', 1),
 ('krølle', 1),
 ('bøjelig', 1),
 ('lydløs', 1),
 ('enkel', 1),
 ('beslægtet', 1),
 ('forvirre', 1),
 ('Næse', 1),
 ('fiks', 1),
 ('hjemløs', 1),
 ('omhyggelig', 1),
 ('usædvanlig', 1),
 ('febrilsk', 1),
 ('satyragtigt', 1),
 ('nedslaaet', 1),
 ('bestyrtet', 1),
 ('blid', 1),
 ('Lille', 1),
 ('forpint', 1),
 ('svimmel', 1),
 ('gøre', 1),
 ('fjorten', 1),
 ('Fjerne', 1),
 ('idiotisk', 1),
 ('bagvendt', 1),
 ('tavs', 1),
 ('fast', 1),
 ('ubetydelig', 1),
 ('øm', 1),
 ('itu', 1),
 ('let', 1),
 ('ubestemt', 1),
 ('halsstarrig', 1),
 ('sikre', 1),
 ('enkelt', 1),
 ('ligeglad', 1),
 ('demonstrativ', 1),
 ('sandsynlig', 1),
 ('Takt', 1),
 ('ugenert', 1),
 ('God', 1),
 ('berømt', 1),
 ('ydre', 1),
 ('begave', 1),
 ('retfærdig', 1),
 ('sen', 1),
 ('faste', 1),
 ('modbydelig', 1),
 ('uartigste', 1),
 ('ranke', 1),
 ('straalende', 1),
 ('lidenskabeligste', 1),
 ('hidsig', 1),
 ('slanke', 1),
 ('indflydelsesrig', 1),
 ('hovedsagelig', 1),
 ('28.', 1),
 ('utilpas', 1),
 ('pudre', 1),
 ('uudforskeligt', 1),
 ('forkrøble', 1),
 ('utilfreds', 1),
 ('spotte', 1),
 ('Mindre', 1),
 ('anstødelig', 1),
 ('tomt', 1),
 ('heftig', 1),
 ('fejl', 1),
 ('lave', 1),
 ('Ejendomme', 1),
 ('smaalig', 1),
 ('29.', 1),
 ('hvidt', 1),
 ('Hertuginde', 1),
 ('herlig', 1),
 ('Hensigt', 1),
 ('uvenlig', 1),
 ('sjette', 1),
 ('sammenhængende', 1),
 ('snavse', 1),
 ('taageindhyllede', 1),
 ('pragtfuldeste', 1),
 ('skjule', 1),
 ('pompøs', 1),
 ('21.', 1),
 ('personlig', 1),
 ('Doges', 1),
 ('spids', 1),
 ('karakteristisk', 1)]

Then we make a dataframe from this list:

In [20]:
df = pd.DataFrame(adjs_tally.most_common(), columns=['adj', 'count'])
df[:100]

             adj  count
0           vild    286
1           alle     97
2            alt     89
3          megen     77
4            god     70
5         gammel     68
6           smuk     63
7           stor     61
8          lille     61
9           hele     60
10          gift     35
11          glad     31
12          mere     31
13         samme     29
14        sikker     28
15        mangen     27
16          søde     27
17         mulig     26
18        dejlig     26
19       kedelig     24
20          kold     24
21         først     24
22           høj     23
23         bange     23
24        sidste     22
25           ung     22
26         vride     22
27          gode     22
28          kære     22
29      stakkels     21
30          sand     21
31         yndig     21
32        eneste     20
33    elskværdig     20
34      lykkelig     20
35     ulykkelig     20
36          unge     19
37        venlig     19
38            eg     18
39          nødt     18
40      underlig     18
41         godte     17
42        umulig     17
43     behagelig     16
44            al     16
45          slem     16
46          sort     15
47        færdig     15
48          blaa     15
49        morsom     14
50            vi     14
51          rødt     14
52         lange     14
53        rædsom     13
54     frygtelig     12
55        nervøs     12
56    forskellig     12
57           rød     12
58    anderledes     12
59   vidunderlig     12
60         flere     11
61            ny     11
62       nydelig     11
63         stærk     10
64          halv     10
65          Kære     10
66           dum     10
67     vanskelig     10
68       forkøle     10
69    Slangepige     10
70     latterlig      9
71           ren      9
72     pragtfuld      9
73        stille      9
74         rolig      9
75         dumme      9
76         stive      9
77      hyggelig      9
78       indtage      9
79          klog      9
80        høflig      8
81        rigtig      8
82           egn      8
83    ubehagelig      8
84    ligegyldig      8
85        trætte      8
86           ene      8
87          fuld      8
88        grusom      8
89      naturlig      8
90            dø      7
91          mørk      7
92           rar      7
93         passe      7
94  ondskabsfuld      7
95          rase      7
96         næste      7
97           rig      7
98   menneskelig      7
99            le      7

## Get Nouns

| POS   | Description               | Examples                                      |
|:-----:|:-------------------------:|:---------------------------------------------:|
| NOUN  | noun                      | girl, cat, tree, air, beauty                  |

To extract and count nouns, we can follow the same model as above, except we will change our `if` statement to check for POS labels that match "NOUN".

In [21]:
nouns = []
for token in document:
    if token.pos_ == 'NOUN':
        nouns.append(token.lemma_)

nouns_tally = Counter(nouns)

df = pd.DataFrame(nouns_tally.most_common(), columns=['noun', 'count'])
df[:100]

             noun  count
0           kunde    200
1            Øjne     63
2           Aften     56
3             Tid     47
4          Verden     46
5           Maade     46
6           Slags     43
7            Gang     40
8            Mand     40
9          Ansigt     40
10           Sted     36
11         Morgen     36
12            Ord     35
13          Haand     35
14           Haar     34
15           Lyst     34
16            Aar     33
17            Gud     33
18         Middag     33
19        Klokken     33
20           Ting     32
21           Mænd     32
22           Folk     31
23           Barn     29
24            Dag     28
25        Værelse     28
26            Liv     27
27         Stemme     27
28           Brev     26
29         Hjerte     26
30             Te     24
31        Øjeblik     24
32         Venner     24
33         Frøken     24
34           Dage     23
35          Døren     23
36          Livet     22
37          Stuen     22
38          Moder     21
39        Følelse     20
40        Trappen     20
41          Siden     20
42           Pige     20
43    Eftermiddag     19
44           Seng     19
45     Dagligstue     19
46          Væsen     19
47     Vestibulen     18
48         Bordet     18
49         Udtryk     18
50       Hertugen     18
51       Menneske     17
52      Mennesker     17
53            Par     17
54          Vejen     17
55   Eventyrerske     16
56      Kærlighed     16
57        Hovedet     16
58          Novbr     16
59     Øjenvipper     15
60         Farvel     15
61            Bog     14
62            Ret     14
63         Kvinde     14
64          Grund     14
65            Vej     14
66          Smule     14
67            Sag     13
68          Fader     13
69         Lørdag     13
70       Minutter     13
71          Sinde     12
72         Tanker     12
73          Penge     12
74          Tiden     12
75           Side     12
76           Blik     12
77        saadant     12
78           Time     12
79           Dame     12
80       Stilling     12
81          Damer     12
82            Ver     12
83            køn     11
84       Følelser     11
85          Huset     11
86     Spørgsmaal     11
87         Øjnene     11
88       Ansigtet     11
89           Stol     11
90          Hoved     11
91         Person     11
92           Hest     11
93        Selskab     11
94           Børn     11
95      Merrenden     11
96         Resten     10
97          Bøger     10
98  Virkeligheden     10
99          Masse     10

## Get Verbs

| POS   | Description               | Examples                                      |
|:-----:|:-------------------------:|:---------------------------------------------:|
| VERB  | verb                      | run, runs, running, eat, ate, eating          |

To extract and count works of art, we can follow a similar-ish model to the examples above. This time, however, we're going to make our code even more economical and efficient (while still changing our `if` statement to match the POS label "VERB").

:::{admonition} Python Review
:class: pythonreview

We can use a [*list comprehension*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/Python/More-Lists-Loops.html#List-Comprehensions) to get our list of verbs in a single line of code! Closely examine the first line of code below:
:::

In [22]:
verbs = [token.lemma_ for token in document if token.pos_ == 'VERB']

verbs_tally = Counter(verbs)

df = pd.DataFrame(verbs_tally.most_common(), columns=['verb', 'count'])
df[:100]

        verb  count
0       sige    742
1       være    342
2      komme    321
3       have    263
4         se    255
5       gøre    182
6        saá    158
7        véd    118
8        hav    101
9        tro    101
10        gå    100
11      føle     90
12      vide     84
13       gaa     76
14    spørge     74
15       tag     71
16     tænke     68
17     sidde     68
18   begynde     66
19      lade     57
20    skrive     56
21      tale     55
22     rejse     54
23     tælle     53
24      gift     52
25       faa     51
26        gø     51
27      syne     51
28     sætte     50
29     elske     50
30     synes     49
31     holde     47
32      høre     47
33  fortælle     45
34     svare     43
35      give     41
36       tog     41
37     vente     41
38        lo     40
39     kysse     39
40        få     37
41     kende     37
42      faar     35
43     finde     35
44      lide     34
45    antage     33
46     holdt     33
47       stå     33
48      more     28
49   udbryde     27
50       lod     26
51   forsøge     26
52     spise     26
53     ville     25
54    glemme     24
55     blive     23
56     passe     23
57    træffe     23
58     bryde     23
59      bede     23
60     ønske     23
61      leve     22
62      hade     22
63        bo     22
64    haaber     21
65     kalde     20
66      vise     20
67   forstaa     20
68      mene     20
69     gaaet     20
70      tage     20
71      love     19
72      køre     19
73     lægge     18
74    bringe     18
75  forelske     17
76     falde     17
77    behøve     17
78     faaet     17
79    spille     16
80   indbyde     16
81      hørt     16
82      gaar     15
83        le     15
84      lære     15
85     lukke     15
86     vende     15
87      læst     14
88     kunne     14
89    hjælpe     14
90      røre     14
91   forlade     14
92     gifte     13
93      møde     13
94      læse     13
95    skulle     13
96     pakke     13
97     huske     13
98      bøje     13
99     ærgre     12

# Keyword Extraction

## Get Sentences with Keyword

spaCy can also identify sentences in a document. To access sentences, we can iterate through `document.sents` and pull out the `.text` of each sentence.

We can use spaCy's sentence-parsing capabilities to extract sentences that contain particular keywords, such as in the function below. Note that the function assumes that the keyword provided will be exactly the same as it appears in the text (e.g. matching all inflection for case, number, gender, etc. As a Spanish example, if you use `bueno` as the keyboard, it won't match `buena` or `buenos`.)

With the function `find_sentences_with_keyword()`, we will iterate through `document.sents` and pull out any sentence that contains a particular "keyword." Then we will display these sentence with the keywords bolded.

In [23]:
import re
from IPython.display import Markdown, display

In [24]:
def find_sentences_with_keyword(keyword, document):
    
    #Iterate through all the sentences in the document and pull out the text of each sentence
    for sentence in document.sents:
        sentence = sentence.text
        
        #Check to see if the keyword is in the sentence (and ignore capitalization by making both lowercase)
        if keyword.lower() in sentence.lower():
            
            #Use the regex library to replace linebreaks and to make the keyword bolded, again ignoring capitalization
            sentence = re.sub('\n', ' ', sentence)
            sentence = re.sub(f"{keyword}", f"**{keyword}**", sentence, flags=re.IGNORECASE)
            
            display(Markdown(sentence))

In [25]:
find_sentences_with_keyword(keyword="godt", document=document)

Jeg har læst alt muligt om det i en Bog; det er at se **godt** ud, og ikke at have noget at leve af, og dog have Fornøjelse af Livet -- og det har jeg i Sinde!

Jeg har ganske vist ingenting at leve af, for man kan ikke regne 300 Pund om Aaret for noget videre -- jeg er overordentlig køn, og jeg véd det **godt**, og jeg forstaar at sætte mit Haar og tage mine Hatte paa og den Slags Ting, saa jeg er naturligvis Eventyrerske!

Jeg er tyve Aar, og lige indtil forrige Uge, da Fru Carruthers blev syg og døde paa én og samme Dag, havde jeg det sommetider meget behageligt, naar hun var i **godt** Humør.

Naar det bliver mørkt, og jeg er alene her oppe, spekulerer jeg ofte paa, hvorledes det vilde have været, hvis jeg havde haft nogle -- men jeg tror, at jeg er af den Slags Katte, som ikke vilde have kommet videre **godt** ud af det med dem -- saa det er maaske bedst saaledes, hvis jeg bare havde -- for Eksempel en smuk Tante til at holde af mig, det kunde have været rart.

Jeg er ikke af en Type, som enhver synes **godt** om.

Da man nu kan gøre, hvad man vil, naar man er gift, haaber jeg virkelig, at Hr. Carruthers vil synes **godt** om mig, og saa bliver alt **godt**!

For -- jeg kan lige saa **godt** sige det med det samme -- det gik ikke.

En høj Mand, der saá forfærdelig **godt** ud, med et glatraget Ansigt og Træk som skaarne ud i Sten.

Hvor havde jeg nogensinde kunnet tænke paa at gifte mig med en Mand, som jeg ikke kendte, blot for at sikre mig et **godt** Hjem!

Heldigvis kan han aldrig ane, at jeg har været villig til at tage ham -- min Forstillelsesevne har hjulpet mig **godt**.

Grunden vilde det passe meget **godt**, hvis De giftede Dem med mig --

-- De kunde bo her og have en sikker Stilling, og jeg kunde komme af og til og se, om De havde det **godt**."

Aa, jeg véd **godt**, at De synes, det er dumt," jeg standsede ham, da han var ved at tale; "men da det naturligvis alligevel ikke varer ved, synes jeg, det kunde være rart at begynde paa den Maade, synes De ikke?"

Han saá overordentlig **godt** ud, som han stod dèr med Ansigtet vendt imod det svindende Lys.

"Jeg kan **godt** lide dette Værelse.

"Jeg haaber, at De ikke bliver ked af det," sagde han, "men en af mine Venner, Lord Robert Vavasour, kommer i Eftermiddag -- han -- forstaar sig meget **godt** paa Malerier.

Jeg kan **godt** lide det Udseende, smal om Livet og smukke Skuldre, og han ser ud, som om han var smidig som en Slange, og dog kunde brække Ildragere midt over, ligesom Hr. Rochester i "Jane Eyre".

Jeg kan **godt** lide hans Stemme -- og han er saa fuldstændig _sans gêne_, at der slet ingen Vanskeligheder er.

Jeg var saa drillevorn, som jeg kunde være -- sympatisk optaget af gamle Bartons lange Historier, og jeg saá kun en Gang imellem paa de to andre gennem mine Øjenvipper -- medens jeg talte paa den pæneste, ærbareste Maade, saa jeg er sikker paa, at selv Lady Katherine Montgomerie -- en af vore Naboersker -- vilde have syntes **godt** om det.

Det syntes jeg **godt** om!

"Jeg synes ikke, du er **godt** Selskab for Frøken Evangeline.

"Ikke **godt** Selskab!" udbrød Lord Robert.

I Morges vaagnede jeg med Hovedpine og saá, at Regnen piskede mod Vinduerne, og det var Taage og Slud -- det passede rigtig **godt** til den femte November.

Det var ikke videre **godt** skrevet, og jeg havde aldrig brudt mig meget om Lady Katherine; men det var ret venligt og passede saa udmærket sammen med mine Planer.

Jeg takkede ham, og han trykkede min Haand saa venligt -- jeg kan **godt** lide Lord Robert.

Og medens rødt Haar ser meget **godt** ud paa mig, synes jeg, at en Mand med rødt Haar er det grimmeste i Verden.

Det var virkelig meget vanskeligt at finde paa noget at sige, og jeg kan **godt** forstaa, at der er Folk, der bliver befippede, naar de bliver pint saadan.

I det mindste -- De véd **godt** -- jeg synes, der er lidt kedeligt paa Landet -- synes De ikke ogsaa?

det beroligede ham, og han sagde alvorligt:  "Jo, det kunde vist være lige saa **godt**.

Jeg takkede hende og sagde, at det var slet ikke nødvendigt, da jeg jo maatte vænne mig til at se Mennesker; jeg kunde ikke gøre Regning paa at træffe Folk, der tænkte saa venligt som hun, jeg kunde lige saa **godt** straks forsøge paa at vænne mig til det.

Jeg haaber, De har det **godt** og ikke blev forkølet paa Køreturen.

"Hvad skal jeg gøre, Katherine?" sagde han lidt efter; "den forbistrede Fyr, Campion, kommer ikke i næste Uge, og han er min bedste Skytte; med saa kort Varsel er det umuligt at faa én, der skyder lige saa **godt**."

Den vilde naturligvis være for snæver til Dem," sagde jeg ydmygt, "men det er ellers et meget **godt** Mønster, og man sprænger den ikke, naar man strækker Armene i Vejret.

Hun smilede til ham, hun kan øjensynlig meget **godt** lide ham.

Han har det mest indtagende Væsen, og man synes straks, at man kender ham meget **godt**; af og til ser han én lige ind i Øjnene med en forbavsende Frejdighed.

Jeg kan **godt** lide at se ham se nedad; hans Øjenvipper er saa latterligt lange og krøllede, de er ikke sorte som mine og Hr. Carruthers, men mørkebrune og bløde og skyggede, og jeg véd ikke rigtig, hvorfor de er saa tiltrækkende.

Nu vilde jeg ønske, at jeg den Gang havde haft Mod til at sige rent ud, at jeg **godt** kunde lide Lord Robert, og at jeg ikke vilde slutte nogen Overenskomst; men man er undertiden ubesindig, naar man bliver overrasket.

Men hun var forfærdelig venlig imod mig og yndig, og hun har indbudt mig til at komme og besøge sig og meget andet, saa det er nok altsammen **godt**.

Det kan **godt** være, at det er noget aldeles forfærdeligt!

"Det er sørgeligt, at den kære Janthe har den uregelmæssige Vane at drikke Te paa sit Værelse -- hun har slet ikke **godt** af det," etc., etc.; men Gud ske Lov, jeg var snart ude i Vestibulen, hvor hendes Pige stod og ventede paa mig.

"Jeg vil ikke gøre nogen Fortræd, med mindre de gør mig Fortræd først -- og jeg kan **godt** lide Dem, De er saa smuk.

"Saa er det **godt**.

Jeg var bange for Robert i Aftes, fordi jeg holder saa meget af ham; men De var sød efter Middag, og nu bliver det nok **godt** altsammen; jeg fortalte ham, at De sandsynligvis skulde giftes med Malcolm Montgomerie, og at han ikke maatte blande sig i det."

Det lød **godt** nok, og dog havde jeg en Følelse af, at jeg hellere vilde sige Nej, og hvis Tonen havde været Spor af beskyttende, havde jeg straks gjort det.

"Jeg vil ikke behandles paa den Maade, De véd **godt**, at jeg kun er kommet her for Deres Skyld.

Skæbnen syntes at modsætte sig, at Lord Robert talte til mig -- selv naar han forsøgte paa det -- og jeg følte, at jeg maatte være ekstra kold og afskyelig, fordi jeg -- naa, jeg kan lige saa **godt** sige det -- synes, at han er saa indtagende.

Hun var saa sød imod mig, at det næsten saá ud, som om hun gerne vilde gøre **godt** igen, at hun ikke vilde lade mig lege med Lord Robert.

Indtil da havde jeg undgaaet hans Tilnærmelser ganske **godt**; men det Løfte, jeg havde givet ham, hang stadig over Hovedet paa mig.

"Jeg kan **godt** gaa i Teatret med Dem i Morgen Aften," sagde han.

Indtil nu -- sagde hun til Lady Ver -- havde Fru Carruthers naturligvis opdraget mig meget omhyggeligt og passet **godt** paa mig, men hun bifaldt ikke hendes Anskuelser.

Han ser ganske **godt** ud, fiks og velklædt som Lord Robert, men han har ikke den smukke Skikkelse.

Jeg kan **godt** lide at se alt paa sin rette Plads -- som i Lord Roberts Skikkelse.

Lady Ver kan ikke videre **godt** lide hende, fortalte hun mig i Toget, men hun var nødt til at telegrafere til hende om at komme, da hun ikke med saa kort Varsel kunde faa fat i en anden, som Hr. Campion kunde lide.

Fru Fairfax blev vred, fordi Hr. Campion vilde tale med mig, men da jeg ikke syntes videre **godt** om hende, brød jeg mig ikke om det, men morede mig.

Jeg følte, at mine Øjne flammede imod ham, men jeg havde en Klump i Halsen; jeg vilde ikke være blevet fornærmet, hvis det havde været enhver anden -- kun vred -- men han havde været saa ærbødig og hensynsfuld imod mig paa Branches -- og jeg havde saa **godt** kunnet lide ham.

"Ja, det vil De have **godt** af, kære Barn," sagde hun fornøjeligt, "saa vil jeg hvile mig her og pleje min Forkølelse."

"De véd meget **godt**, hvad jeg mener, hvad har de fortalt Dem om mig?"

"Ikke andet, end at der er en henrivende fransk Dame, som tilbeder Dem, og som De holder forfærdelig meget af -- og jeg sympatiserer med Dem -- jeg kan **godt** lide franske Damer, de sætter deres Hatte saa nydeligt."

"Hvilken latterlig Sladder -- jeg tror ikke, at Park Street er et **godt** Sted for Dem at bo.

"Ja, det kan jeg **godt**," sagde jeg.

"Vi haaber, du har sovet **godt** og har haft en behagelig Rejse over Søen."

Jeg kan **godt** forstaa, at hun foretrækker -- Lord Robert.

Han var blevet forkølet, sagde han, og var gaaet ud for at faa et Glas Cognak, og nu havde han det helt **godt**, og vilde vi nu ikke komme med og spise til Aften, og mange andre elskværdige Ting, medens han saá paa hende med den inderligste Hengivenhed -- det var, som om jeg ikke eksisterede.

Han faar mig til at tro paa alt, hvad der er **godt** og hæderligt.

"Og det var **godt** nok til hende, den fortryllende, djævelske Dæmon!"

"Men han tilbeder mig paa sin Maade, og han har nok en ny Diamantring med til mig for at gøre det **godt** igen -- nu skal De se til Lunch.

De vil sandsynligvis faa det dejligt sammen med ham, og holde ham forelsket i Dem i mange Aar, fordi De ikke er forelsket i ham, og han vil passe **godt** paa, at De ikke ser paa nogen anden.

Vi talte ikke i nogle Minutter, saa sagde hun muntert:  "De har gjort mit Hoved bedre, Deres Strygninger er vidunderlige; trods alt kan jeg **godt** lide Dem, Slangepige.

Lunchen gik meget **godt**.

"Sandheden er, De kan ikke være den mindste Smule ekscentrisk eller ukonventionel, hvis De ser **godt** ud og er ugift," fortsatte hun, "De kan maaske knipse med Fingrene ad Samfundet, men hvis De gør det, faar De det ikke behageligt, og alle Mændene vil enten forsvare Dem paa en taabelig Maade eller være uforskammede imod Dem.

Jeg takkede hende, saa **godt** jeg kunde.

"Kunde De da **godt** lide, at jeg skulde se anderledes ud?

Og denne søde Dames Øjne smeltede hen i Ømhed, da hun talte om Fortiden -- skønt hun ikke kender mig **godt** nok til at sige mere.

En Godhed og Elskelighed som denne passer ikke Mændene saa **godt** som Luner, lader det til.

Jeg glemte helt, at jeg var en hjemløs Vandrer, og jeg kom tilbage til Claridges omtrent Klokken halv fem i næsten **godt** Humør.

Jeg har fortalt mig selv, hvor køn han er -- og hvor jeg syntes **godt** om ham paa Branches -- men det var før -- ja, jeg kan lige saa **godt** skrive det -- før Lord Robert kom.

"Ingenting," sagde jeg, saa **godt** jeg kunde, og forsøgte paa at trække min Hat ned over Øjnene.

For, som du meget **godt** maa vide, elsker jeg dig."

det er **godt** nok, min Skat, hun maa jo vide alt om din Familie, og kan fortælle det til Torquilstone.

"Er det **godt**?" spurgte jeg og rakte det til Robert, medens jeg skrev udenpaa Konvolutten.

Pas **godt** paa dig selv!

"Kort og **godt**, han har absolut nægtet at have noget at gøre med Sagen; han siger, at jeg skal ikke vente noget mere fra ham, og vi er skilt fra hinanden for bestandig!"

"Jeg forstaar mig forholdsvis **godt** paa at bedømme Karakterer.

Jeg vil give ham mig selv, og vi skal komme meget **godt** ud af det uden Dem!

Saa prøvede jeg paa at fortælle det, saa **godt** jeg kunde, og de hørte aandeløst efter.

Hvad i Alverden er noget som helst andet **godt** for i Livet, end at være vanvittig forelsket, saaledes som vi er det.

## Get Keyword in Context

We can also find out about a keyword's more immediate context — its neighboring words to the left and right — and we can fine-tune our search with POS tagging.

To do so, we will first create a list of what's called *ngrams*. "Ngrams" are any sequence of *n* tokens in a text. They're an important concept in computational linguistics and NLP. (Have you ever played with [Google's *Ngram* Viewer](https://books.google.com/ngrams)?)

Below we're going to make a list of *bigrams*, that is, all the two-word combinations from the sample text. We're going to use these bigrams to find the neighboring words that appear alongside particular keywords.

In [27]:
#Make a list of tokens and POS labels from document if the token is a word 
tokens_and_labels = [(token.text, token.pos_) for token in document if token.is_alpha]

In [28]:
#Make a function to get all two-word combinations
def get_bigrams(word_list, number_consecutive_words=2):
    
    ngrams = []
    adj_length_of_word_list = len(word_list) - (number_consecutive_words - 1)
    
    #Loop through numbers from 0 to the (slightly adjusted) length of your word list
    for word_index in range(adj_length_of_word_list):
        
        #Index the list at each number, grabbing the word at that number index as well as N number of words after it
        ngram = word_list[word_index : word_index + number_consecutive_words]
        
        #Append this word combo to the master list "ngrams"
        ngrams.append(ngram)
        
    return ngrams

In [29]:
bigrams = get_bigrams(tokens_and_labels)

Let's take a peek at the bigrams:

In [30]:
bigrams[5:20]

[[('HAAR', 'NOUN'), ('ELINOR', 'PROPN')],
 [('ELINOR', 'PROPN'), ('GLYN', 'PROPN')],
 [('GLYN', 'PROPN'), ('EVANGELINES', 'PROPN')],
 [('EVANGELINES', 'PROPN'), ('GENVORDIGHEDER', 'NOUN')],
 [('GENVORDIGHEDER', 'NOUN'), ('AUTORISERET', 'NOUN')],
 [('AUTORISERET', 'NOUN'), ('OVERSÆTTELSE', 'NOUN')],
 [('OVERSÆTTELSE', 'NOUN'), ('FOR', 'ADP')],
 [('FOR', 'ADP'), ('NORGE', 'PROPN')],
 [('NORGE', 'PROPN'), ('OG', 'CCONJ')],
 [('OG', 'CCONJ'), ('DANMARK', 'PROPN')],
 [('DANMARK', 'PROPN'), ('AF', 'ADP')],
 [('AF', 'ADP'), ('HEDVIG', 'PROPN')],
 [('HEDVIG', 'PROPN'), ('MAGNUSSEN', 'PROPN')],
 [('MAGNUSSEN', 'PROPN'), ('NY', 'ADJ')],
 [('NY', 'ADJ'), ('UDGAVE', 'NOUN')]]

Now that we have our list of bigrams, we're going to make a function `get_neighbor_words()`. This function will return the most frequent words that appear next to a particular keyword. The function can also be fine-tuned to return neighbor words that match a certain part of speech by changing the `pos_label` parameter.

In [31]:
def get_neighbor_words(keyword, bigrams, pos_label = None):
    
    neighbor_words = []
    keyword = keyword.lower()
    
    for bigram in bigrams:
        
        #Extract just the lowercased words (not the labels) for each bigram
        words = [word.lower() for word, label in bigram]        
        
        #Check to see if keyword is in the bigram
        if keyword in words:
            
            for word, label in bigram:
                
                #Now focus on the neighbor word, not the keyword
                if word.lower() != keyword:
                    #If the neighbor word matches the right pos_label, append it to the master list
                    if label == pos_label or pos_label == None:
                        neighbor_words.append(word.lower())
    
    return Counter(neighbor_words).most_common()

In [32]:
get_neighbor_words("godt", bigrams)

[('saa', 12),
 ('kan', 12),
 ('lide', 12),
 ('meget', 10),
 ('jeg', 9),
 ('ud', 8),
 ('det', 7),
 ('og', 6),
 ('om', 6),
 ('paa', 5),
 ('nok', 5),
 ('videre', 4),
 ('véd', 3),
 ('er', 3),
 ('af', 3),
 ('humør', 2),
 ('synes', 2),
 ('sige', 2),
 ('et', 2),
 ('mig', 2),
 ('at', 2),
 ('syntes', 2),
 ('selskab', 2),
 ('ikke', 2),
 ('forstaa', 2),
 ('altsammen', 2),
 ('men', 2),
 ('igen', 2),
 ('ganske', 2),
 ('se', 1),
 ('i', 1),
 ('alt', 1),
 ('forfærdelig', 1),
 ('hjem', 1),
 ('nu', 1),
 ('hvis', 1),
 ('overordentlig', 1),
 ('rigtig', 1),
 ('til', 1),
 ('skrevet', 1),
 ('de', 1),
 ('straks', 1),
 ('ja', 1),
 ('mønster', 1),
 ('kunde', 1),
 ('være', 1),
 ('lød', 1),
 ('gøre', 1),
 ('gaa', 1),
 ('passet', 1),
 ('kunnet', 1),
 ('have', 1),
 ('hvad', 1),
 ('sted', 1),
 ('sagde', 1),
 ('sovet', 1),
 ('helt', 1),
 ('var', 1),
 ('passe', 1),
 ('sir', 1),
 ('ser', 1),
 ('da', 1),
 ('som', 1),
 ('næsten', 1),
 ('skrive', 1),
 ('maa', 1),
 ('spurgte', 1),
 ('pas', 1),
 ('han', 1),
 ('forholdsvis', 1),
 ('andet', 1),
 ('for', 1)]

In [33]:
get_neighbor_words("godt", bigrams, pos_label='VERB')

[('lide', 12),
 ('véd', 3),
 ('synes', 2),
 ('sige', 2),
 ('syntes', 2),
 ('forstaa', 2),
 ('se', 1),
 ('skrevet', 1),
 ('kan', 1),
 ('være', 1),
 ('lød', 1),
 ('gøre', 1),
 ('gaa', 1),
 ('passet', 1),
 ('have', 1),
 ('sagde', 1),
 ('sovet', 1),
 ('er', 1),
 ('passe', 1),
 ('ser', 1),
 ('skrive', 1),
 ('spurgte', 1),
 ('pas', 1)]

## Your Turn!

Try out `find_sentences_with_keyword()` and `get_neighbor_words` with your own keywords of interest.

In [ ]:
find_sentences_with_keyword(keyword="YOUR KEY WORD", document=document)

In [ ]:
get_neighbor_words(keyword="YOUR KEY WORD", bigrams, pos_label=None)